/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGRTCACHEGEOMETRYSTOREFIELDS_H_
#define _OSGRTCACHEGEOMETRYSTOREFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribRRTDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class RTCacheGeometryStore;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! RTCacheGeometryStorePtr

OSG_GEN_CONTAINERPTR(RTCacheGeometryStore);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpContribRRTFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<RTCacheGeometryStorePtr> :
    public FieldTraitsFCPtrBase<RTCacheGeometryStorePtr>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<RTCacheGeometryStorePtr>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBRRT_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFRTCacheGeometryStorePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFRTCacheGeometryStorePtr"; }
};

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStorePtr, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdRTCacheGeometryStorePtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<RTCacheGeometryStorePtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribRRTFieldSingle */

typedef PointerSField<RTCacheGeometryStorePtr,
                      RecordedRefCountPolicy  > SFRecRTCacheGeometryStorePtr;
typedef PointerSField<RTCacheGeometryStorePtr,
                      UnrecordedRefCountPolicy> SFUnrecRTCacheGeometryStorePtr;
typedef PointerSField<RTCacheGeometryStorePtr,
                      WeakRefCountPolicy      > SFWeakRTCacheGeometryStorePtr;
typedef PointerSField<RTCacheGeometryStorePtr,
                      NoRefCountPolicy        > SFUncountedRTCacheGeometryStorePtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribRRTFieldMulti */

typedef PointerMField<RTCacheGeometryStorePtr,
                      RecordedRefCountPolicy  > MFRecRTCacheGeometryStorePtr;
typedef PointerMField<RTCacheGeometryStorePtr,
                      UnrecordedRefCountPolicy> MFUnrecRTCacheGeometryStorePtr;
typedef PointerMField<RTCacheGeometryStorePtr,
                      WeakRefCountPolicy      > MFWeakRTCacheGeometryStorePtr;
typedef PointerMField<RTCacheGeometryStorePtr,
                      NoRefCountPolicy        > MFUncountedRTCacheGeometryStorePtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGRTCACHEGEOMETRYSTOREFIELDS_H_ */
