/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGRTCACHEGEOMETRYSTOREFIELDS_H_
#define _OSGRTCACHEGEOMETRYSTOREFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribRRTDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class RTCacheGeometryStore;

OSG_GEN_CONTAINERPTR(RTCacheGeometryStore);
/*! \ingroup GrpContribRRTFieldTraits
    \ingroup GrpLibOSGContribRRT
 */
template <>
struct FieldTraits<RTCacheGeometryStore *, nsOSG> :
    public FieldTraitsFCPtrBase<RTCacheGeometryStore *, nsOSG>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<RTCacheGeometryStore *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBRRT_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakRTCacheGeometryStorePtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheGeometryStore *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdRTCacheGeometryStorePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheGeometryStore *,
                      RecordedRefCountPolicy, nsOSG  > SFRecRTCacheGeometryStorePtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheGeometryStore *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecRTCacheGeometryStorePtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheGeometryStore *,
                      WeakRefCountPolicy, nsOSG      > SFWeakRTCacheGeometryStorePtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheGeometryStore *,
                      NoRefCountPolicy, nsOSG        > SFUncountedRTCacheGeometryStorePtr;


/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheGeometryStore *,
                      RecordedRefCountPolicy, nsOSG  > MFRecRTCacheGeometryStorePtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheGeometryStore *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecRTCacheGeometryStorePtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheGeometryStore *,
                      WeakRefCountPolicy, nsOSG      > MFWeakRTCacheGeometryStorePtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheGeometryStore *,
                      NoRefCountPolicy, nsOSG        > MFUncountedRTCacheGeometryStorePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFRecRTCacheGeometryStorePtr : 
    public PointerSField<RTCacheGeometryStore *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUnrecRTCacheGeometryStorePtr : 
    public PointerSField<RTCacheGeometryStore *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFWeakRTCacheGeometryStorePtr :
    public PointerSField<RTCacheGeometryStore *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUncountedRTCacheGeometryStorePtr :
    public PointerSField<RTCacheGeometryStore *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFRecRTCacheGeometryStorePtr :
    public PointerMField<RTCacheGeometryStore *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUnrecRTCacheGeometryStorePtr :
    public PointerMField<RTCacheGeometryStore *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFWeakRTCacheGeometryStorePtr :
    public PointerMField<RTCacheGeometryStore *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUncountedRTCacheGeometryStorePtr :
    public PointerMField<RTCacheGeometryStore *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGRTCACHEGEOMETRYSTOREFIELDS_H_ */
