/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class RTTextureTarget!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILERTTEXTURETARGETINST

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>
#include "boost/bind.hpp"

#include <OSGConfig.h>



#include <OSGTextureObjChunk.h> // TexObjChunk Class

#include "OSGRTTextureTargetBase.h"
#include "OSGRTTextureTarget.h"

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::RTTextureTarget
    
 */

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

/*! \var TextureObjChunkPtr RTTextureTargetBase::_sfTexObjChunk
    
*/


void RTTextureTargetBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFTextureObjChunkPtr::Description(
        SFTextureObjChunkPtr::getClassType(),
        "TexObjChunk",
        "",
        TexObjChunkFieldId, TexObjChunkFieldMask,
        false,
        Field::SFDefaultFlags,
        static_cast<FieldEditMethodSig>(&RTTextureTargetBase::editHandleTexObjChunk),
        static_cast<FieldGetMethodSig >(&RTTextureTargetBase::getHandleTexObjChunk));

    oType.addInitialDesc(pDesc);
}


RTTextureTargetBase::TypeObject RTTextureTargetBase::_type(
    RTTextureTargetBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    (ProtoBundleCreateF) &RTTextureTargetBase::createEmpty,
    RTTextureTarget::initMethod,
    (InitalInsertDescFunc) &RTTextureTargetBase::classDescInserter,
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"RTTextureTarget\"\n"
    "    parent=\"RTTarget\"\n"
    "    library=\"ContribRRT\"\n"
    "    pointerfieldtypes=\"single\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    libnamespace=\"OSG\"\n"
    ">\n"
    "    <Field\n"
    "        name=\"TexObjChunk\"\n"
    "        type=\"TextureObjChunkPtr\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldBundleType &RTTextureTargetBase::getType(void)
{
    return _type;
}

const FieldBundleType &RTTextureTargetBase::getType(void) const
{
    return _type;
}

UInt32 RTTextureTargetBase::getContainerSize(void) const
{
    return sizeof(RTTextureTarget);
}

/*------------------------- decorator get ------------------------------*/


//! Get the RTTextureTarget::_sfTexObjChunk field.
const SFTextureObjChunkPtr *RTTextureTargetBase::getSFTexObjChunk(void) const
{
    return &_sfTexObjChunk;
}





/*------------------------------ access -----------------------------------*/

UInt32 RTTextureTargetBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (TexObjChunkFieldMask & whichField))
    {
        returnValue += _sfTexObjChunk.getBinSize();
    }

    return returnValue;
}

void RTTextureTargetBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (TexObjChunkFieldMask & whichField))
    {
        _sfTexObjChunk.copyToBin(pMem);
    }
}

void RTTextureTargetBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (TexObjChunkFieldMask & whichField))
    {
        _sfTexObjChunk.copyFromBin(pMem);
    }
}

//! create an empty new instance of the class, do not copy the prototype
RTTextureTargetP RTTextureTargetBase::createEmpty(void)
{
    RTTextureTargetP returnValue;

    newPtr<RTTextureTarget>(returnValue);

    return returnValue;
}

FieldBundleP RTTextureTargetBase::shallowCopy(void) const
{
    RTTextureTargetP returnValue;

    newPtr(returnValue, dynamic_cast<const RTTextureTarget *>(this));

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

RTTextureTargetBase::RTTextureTargetBase(void) :
    Inherited(),
    _sfTexObjChunk            (NullFC)
{
}

RTTextureTargetBase::RTTextureTargetBase(const RTTextureTargetBase &source) :
    Inherited(source),
    _sfTexObjChunk            ()
{
}

/*-------------------------- destructors ----------------------------------*/

RTTextureTargetBase::~RTTextureTargetBase(void)
{
}

void RTTextureTargetBase::onCreate(const RTTextureTarget *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {

        this->setTexObjChunk(source->getTexObjChunk());
    }
}

void RTTextureTargetBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<RTTextureTarget *>(this)->setTexObjChunk(NullFC);
}

GetFieldHandlePtr RTTextureTargetBase::getHandleTexObjChunk     (void) const
{
    SFTextureObjChunkPtr::GetHandlePtr returnValue(
        new  SFTextureObjChunkPtr::GetHandle(
             &_sfTexObjChunk, 
             this->getType().getFieldDesc(TexObjChunkFieldId)));

    return returnValue;
}

EditFieldHandlePtr RTTextureTargetBase::editHandleTexObjChunk    (void)
{
    SFTextureObjChunkPtr::EditHandlePtr returnValue(
        new  SFTextureObjChunkPtr::EditHandle(
             &_sfTexObjChunk, 
             this->getType().getFieldDesc(TexObjChunkFieldId)));

    returnValue->setSetMethod(boost::bind(&RTTextureTarget::setTexObjChunk, this, _1));

    editSField(TexObjChunkFieldMask);

    return returnValue;
}



OSG_END_NAMESPACE

#include "OSGSFieldAdaptor.ins"

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<RTTextureTargetP>::_type("RTTextureTargetP", "RTTargetP");
#endif

OSG_FIELDTRAITS_GETTYPE(RTTextureTargetP)

OSG_FIELD_DLLEXPORT_DEF2(SFieldAdaptor, RTTextureTargetP, SFFieldBundleP);


OSG_END_NAMESPACE
