/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGRTIMAGETARGETFIELDS_H_
#define _OSGRTIMAGETARGETFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribRRTDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class RTImageTarget;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! RTImageTargetPtr

OSG_GEN_CONTAINERPTR(RTImageTarget);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpContribRRTFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<RTImageTarget *> :
    public FieldTraitsFCPtrBase<RTImageTarget *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<RTImageTarget *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBRRT_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFRTImageTargetPtr"; }
};

template<> inline
const Char8 *FieldTraits<RTImageTarget *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRTImageTargetPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTImageTarget *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRTImageTargetPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTImageTarget *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRTImageTargetPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTImageTarget *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRTImageTargetPtr"; 
}


#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<RTImageTargetPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribRRTFieldSingle */

typedef PointerSField<RTImageTarget *,
                      RecordedRefCountPolicy  > SFRecRTImageTargetPtr;
typedef PointerSField<RTImageTarget *,
                      UnrecordedRefCountPolicy> SFUnrecRTImageTargetPtr;
typedef PointerSField<RTImageTarget *,
                      WeakRefCountPolicy      > SFWeakRTImageTargetPtr;
typedef PointerSField<RTImageTarget *,
                      NoRefCountPolicy        > SFUncountedRTImageTargetPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGRTIMAGETARGETFIELDS_H_ */
