/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMETADATAATTACHMENTFIELDS_H_
#define _OSGMETADATAATTACHMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribMetaDataDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MetaDataAttachment;

OSG_GEN_CONTAINERPTR(MetaDataAttachment);
/*! \ingroup GrpMetaDataFieldTraits
    \ingroup GrpLibOSGContribMetaData
 */
template <>
struct FieldTraits<MetaDataAttachment *, nsOSG> :
    public FieldTraitsFCPtrBase<MetaDataAttachment *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MetaDataAttachment *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBMETADATA_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

};

template<> inline
const Char8 *FieldTraits<MetaDataAttachment *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMetaDataAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<MetaDataAttachment *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMetaDataAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<MetaDataAttachment *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMetaDataAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<MetaDataAttachment *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMetaDataAttachmentPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpMetaDataFieldSFields */
typedef PointerSField<MetaDataAttachment *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMetaDataAttachmentPtr;
/*! \ingroup GrpMetaDataFieldSFields */
typedef PointerSField<MetaDataAttachment *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMetaDataAttachmentPtr;
/*! \ingroup GrpMetaDataFieldSFields */
typedef PointerSField<MetaDataAttachment *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMetaDataAttachmentPtr;
/*! \ingroup GrpMetaDataFieldSFields */
typedef PointerSField<MetaDataAttachment *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMetaDataAttachmentPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpMetaDataFieldSFields \ingroup GrpLibOSGContribMetaData */
struct SFRecMetaDataAttachmentPtr : 
    public PointerSField<MetaDataAttachment *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpMetaDataFieldSFields \ingroup GrpLibOSGContribMetaData */
struct SFUnrecMetaDataAttachmentPtr : 
    public PointerSField<MetaDataAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpMetaDataFieldSFields \ingroup GrpLibOSGContribMetaData */
struct SFWeakMetaDataAttachmentPtr :
    public PointerSField<MetaDataAttachment *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpMetaDataFieldSFields \ingroup GrpLibOSGContribMetaData */
struct SFUncountedMetaDataAttachmentPtr :
    public PointerSField<MetaDataAttachment *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMETADATAATTACHMENTFIELDS_H_ */
