MESSAGE(STATUS "Prepare OSGContribSOFA")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake")

INCLUDE(ConfigurePackages.OSGContribSOFA)

IF(NOT OSG_BUILD_DEPENDEND)
  OSG_CONFIGURE_SOFA()

#  OSG_ADD_OPT(CG_FOUND)
#  OSG_ADD_OPT(CG_LIBRARIES_FOUND)
#  OSG_ADD_OPT(CG_LIBRARIES)
#  OSG_ADD_OPT(CG_INCLUDE_DIR)
ENDIF(NOT OSG_BUILD_DEPENDEND)

IF(OSG_WITH_SOFA)
  OSG_CONFIGURE_GLEW()
ENDIF()

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_SOFA 1")

MESSAGE(STATUS "SOFA Status: SOFA: ${OSG_WITH_SOFA}")

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/FindSOFA.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/ConfigurePackages.OSGContribSOFA.cmake"
        DESTINATION share/OpenSG/cmake)

