/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGLABELFOREGROUNDFIELDS_H_
#define _OSGLABELFOREGROUNDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribLabelingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class LabelForeground;

OSG_GEN_CONTAINERPTR(LabelForeground);
/*! \ingroup GrpContribLabelingFieldTraits
    \ingroup GrpLibOSGContribLabeling
 */
template <>
struct FieldTraits<LabelForeground *, nsOSG> :
    public FieldTraitsFCPtrBase<LabelForeground *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<LabelForeground *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBLABELING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdLabelForegroundPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<LabelForeground *,
                      RecordedRefCountPolicy, nsOSG  > SFRecLabelForegroundPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<LabelForeground *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecLabelForegroundPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<LabelForeground *,
                      WeakRefCountPolicy, nsOSG      > SFWeakLabelForegroundPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<LabelForeground *,
                      NoRefCountPolicy, nsOSG        > SFUncountedLabelForegroundPtr;


/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<LabelForeground *,
                      RecordedRefCountPolicy, nsOSG  > MFRecLabelForegroundPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<LabelForeground *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecLabelForegroundPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<LabelForeground *,
                      WeakRefCountPolicy, nsOSG      > MFWeakLabelForegroundPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<LabelForeground *,
                      NoRefCountPolicy, nsOSG        > MFUncountedLabelForegroundPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFRecLabelForegroundPtr : 
    public PointerSField<LabelForeground *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFUnrecLabelForegroundPtr : 
    public PointerSField<LabelForeground *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFWeakLabelForegroundPtr :
    public PointerSField<LabelForeground *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFUncountedLabelForegroundPtr :
    public PointerSField<LabelForeground *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFRecLabelForegroundPtr :
    public PointerMField<LabelForeground *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFUnrecLabelForegroundPtr :
    public PointerMField<LabelForeground *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFWeakLabelForegroundPtr :
    public PointerMField<LabelForeground *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFUncountedLabelForegroundPtr :
    public PointerMField<LabelForeground *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGLABELFOREGROUNDFIELDS_H_ */
