/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGLABELFIELDS_H_
#define _OSGLABELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribLabelingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class Label;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! LabelPtr

OSG_GEN_CONTAINERPTR(Label);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpContribLabelingFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<Label *> :
    public FieldTraitsFCPtrBase<Label *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<Label *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBLABELING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFLabelPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFLabelPtr"; }
};

template<> inline
const Char8 *FieldTraits<Label *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdLabelPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<LabelPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribLabelingFieldSingle */

typedef PointerSField<Label *,
                      RecordedRefCountPolicy  > SFRecLabelPtr;
typedef PointerSField<Label *,
                      UnrecordedRefCountPolicy> SFUnrecLabelPtr;
typedef PointerSField<Label *,
                      WeakRefCountPolicy      > SFWeakLabelPtr;
typedef PointerSField<Label *,
                      NoRefCountPolicy        > SFUncountedLabelPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribLabelingFieldMulti */

typedef PointerMField<Label *,
                      RecordedRefCountPolicy  > MFRecLabelPtr;
typedef PointerMField<Label *,
                      UnrecordedRefCountPolicy> MFUnrecLabelPtr;
typedef PointerMField<Label *,
                      WeakRefCountPolicy      > MFWeakLabelPtr;
typedef PointerMField<Label *,
                      NoRefCountPolicy        > MFUncountedLabelPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGLABELFIELDS_H_ */
