/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGLABELFOREGROUNDFIELDS_H_
#define _OSGLABELFOREGROUNDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribLabelingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class LabelForeground;

#if !defined(OSG_DO_DOC) // created as a dummy class, remove to prevent doubles
//! LabelForegroundPtr

OSG_GEN_CONTAINERPTR(LabelForeground);

#endif

#if !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)
/*! \ingroup GrpContribLabelingFieldTraits
 */
#if !defined(OSG_DOC_DEV_TRAITS)
/*! \hideinhierarchy */
#endif

template <>
struct FieldTraits<LabelForeground *> :
    public FieldTraitsFCPtrBase<LabelForeground *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<LabelForeground *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBLABELING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFLabelForegroundPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFLabelForegroundPtr"; }
};

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakLabelForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<LabelForeground *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdLabelForegroundPtr"; 
}

#if !defined(OSG_DOC_DEV_TRAITS)
/*! \class  FieldTraitsTemplateBase<LabelForegroundPtr, 0>
    \hideinhierarchy
 */
#endif

#endif // !defined(OSG_DO_DOC) || (OSG_DOC_LEVEL >= 3)


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribLabelingFieldSingle */

typedef PointerSField<LabelForeground *,
                      RecordedRefCountPolicy  > SFRecLabelForegroundPtr;
typedef PointerSField<LabelForeground *,
                      UnrecordedRefCountPolicy> SFUnrecLabelForegroundPtr;
typedef PointerSField<LabelForeground *,
                      WeakRefCountPolicy      > SFWeakLabelForegroundPtr;
typedef PointerSField<LabelForeground *,
                      NoRefCountPolicy        > SFUncountedLabelForegroundPtr;
#endif


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_FIELD_TYPEDEFS)
/*! \ingroup GrpContribLabelingFieldMulti */

typedef PointerMField<LabelForeground *,
                      RecordedRefCountPolicy  > MFRecLabelForegroundPtr;
typedef PointerMField<LabelForeground *,
                      UnrecordedRefCountPolicy> MFUnrecLabelForegroundPtr;
typedef PointerMField<LabelForeground *,
                      WeakRefCountPolicy      > MFWeakLabelForegroundPtr;
typedef PointerMField<LabelForeground *,
                      NoRefCountPolicy        > MFUncountedLabelForegroundPtr;
#endif


OSG_END_NAMESPACE

#endif /* _OSGLABELFOREGROUNDFIELDS_H_ */
