/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGLABELFIELDS_H_
#define _OSGLABELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribLabelingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class Label;

OSG_GEN_CONTAINERPTR(Label);
/*! \ingroup GrpContribLabelingFieldTraits
    \ingroup GrpLibOSGContribLabeling
 */
template <>
struct FieldTraits<Label *, nsOSG> :
    public FieldTraitsFCPtrBase<Label *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<Label *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBLABELING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<Label *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdLabelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<Label *,
                      RecordedRefCountPolicy, nsOSG  > SFRecLabelPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<Label *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecLabelPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<Label *,
                      WeakRefCountPolicy, nsOSG      > SFWeakLabelPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<Label *,
                      NoRefCountPolicy, nsOSG        > SFUncountedLabelPtr;


/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<Label *,
                      RecordedRefCountPolicy, nsOSG  > MFRecLabelPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<Label *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecLabelPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<Label *,
                      WeakRefCountPolicy, nsOSG      > MFWeakLabelPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<Label *,
                      NoRefCountPolicy, nsOSG        > MFUncountedLabelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFRecLabelPtr : 
    public PointerSField<Label *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFUnrecLabelPtr : 
    public PointerSField<Label *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFWeakLabelPtr :
    public PointerSField<Label *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFUncountedLabelPtr :
    public PointerSField<Label *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFRecLabelPtr :
    public PointerMField<Label *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFUnrecLabelPtr :
    public PointerMField<Label *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFWeakLabelPtr :
    public PointerMField<Label *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFUncountedLabelPtr :
    public PointerMField<Label *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGLABELFIELDS_H_ */
