/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTLABELFIELDS_H_
#define _OSGTEXTLABELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribLabelingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TextLabel;

OSG_GEN_CONTAINERPTR(TextLabel);

/*! \ingroup GrpContribLabelingFieldTraits
    \ingroup GrpLibOSGContribLabeling
 */
template <>
struct FieldTraits<TextLabel *> :
    public FieldTraitsFCPtrBase<TextLabel *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TextLabel *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBLABELING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTextLabelPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTextLabelPtr"; }
};

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextLabelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextLabel *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextLabelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<TextLabel *,
                      RecordedRefCountPolicy  > SFRecTextLabelPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<TextLabel *,
                      UnrecordedRefCountPolicy> SFUnrecTextLabelPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<TextLabel *,
                      WeakRefCountPolicy      > SFWeakTextLabelPtr;
/*! \ingroup GrpContribLabelingFieldSFields */
typedef PointerSField<TextLabel *,
                      NoRefCountPolicy        > SFUncountedTextLabelPtr;


/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<TextLabel *,
                      RecordedRefCountPolicy  > MFRecTextLabelPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<TextLabel *,
                      UnrecordedRefCountPolicy> MFUnrecTextLabelPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<TextLabel *,
                      WeakRefCountPolicy      > MFWeakTextLabelPtr;
/*! \ingroup GrpContribLabelingFieldMFields */
typedef PointerMField<TextLabel *,
                      NoRefCountPolicy        > MFUncountedTextLabelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFRecTextLabelPtr : 
    public PointerSField<TextLabel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFUnrecTextLabelPtr : 
    public PointerSField<TextLabel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFWeakTextLabelPtr :
    public PointerSField<TextLabel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldSFields \ingroup GrpLibOSGContribLabeling */
struct SFUncountedTextLabelPtr :
    public PointerSField<TextLabel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFRecTextLabelPtr :
    public PointerMField<TextLabel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFUnrecTextLabelPtr :
    public PointerMField<TextLabel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFWeakTextLabelPtr :
    public PointerMField<TextLabel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribLabelingFieldMFields \ingroup GrpLibOSGContribLabeling */
struct MFUncountedTextLabelPtr :
    public PointerMField<TextLabel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTLABELFIELDS_H_ */
