/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DynamicTerrain!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEDYNAMICTERRAININST

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OSGConfig.h>



#include <OSGImage.h> // HeightData Class
#include <OSGImage.h> // TextureData Class
#include <OSGTextureChunk.h> // HeightColorTexture Class

#include "OSGDynamicTerrainBase.h"
#include "OSGDynamicTerrain.h"

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::DynamicTerrain
    
 */

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

/*! \var Int32           DynamicTerrainBase::_sfLevelSize
    
*/

/*! \var ImagePtr        DynamicTerrainBase::_sfHeightData
    
*/

/*! \var Real32          DynamicTerrainBase::_sfHeightDataScale
    
*/

/*! \var Real32          DynamicTerrainBase::_sfHeightDataOffset
    
*/

/*! \var Real32          DynamicTerrainBase::_sfSampleDistance
    
*/

/*! \var ImagePtr        DynamicTerrainBase::_sfTextureData
    
*/

/*! \var TextureChunkPtr DynamicTerrainBase::_sfHeightColorTexture
    
*/

/*! \var Int32           DynamicTerrainBase::_sfSampleUpdateBudget
    
*/

/*! \var bool            DynamicTerrainBase::_sfEnableFrustumCulling
    
*/

/*! \var bool            DynamicTerrainBase::_sfUseGpuRenderer
    
*/

/*! \var bool            DynamicTerrainBase::_sfUseVboExtension
    
*/

/*! \var bool            DynamicTerrainBase::_sfEnableSmoothTransition
    
*/

/*! \var bool            DynamicTerrainBase::_sfShowBoundingBoxes
    
*/

/*! \var bool            DynamicTerrainBase::_sfShowTransitionRegions
    
*/

/*! \var bool            DynamicTerrainBase::_sfDisableUpdate
    
*/

/*! \var std::string     DynamicTerrainBase::_sfCpuVertexProgram
    
*/

/*! \var std::string     DynamicTerrainBase::_sfCpuFragmentProgram
    
*/


void DynamicTerrainBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


#ifdef OSG_1_COMPAT
    typedef const SFInt32 *(DynamicTerrainBase::*GetSFLevelSizeF)(void) const;

    GetSFLevelSizeF GetSFLevelSize = &DynamicTerrainBase::getSFLevelSize;
#endif

    pDesc = new SFInt32::Description(
        SFInt32::getClassType(),
        "levelSize",
        "",
        LevelSizeFieldId, LevelSizeFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFLevelSize),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFLevelSize));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFLevelSize));
#endif

    oType.addInitialDesc(pDesc);

    pDesc = new SFImagePtr::Description(
        SFImagePtr::getClassType(),
        "heightData",
        "",
        HeightDataFieldId, HeightDataFieldMask,
        false,
        Field::SFDefaultFlags,
        static_cast     <FieldEditMethodSig>(&DynamicTerrainBase::invalidEditField),
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFHeightData));

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFReal32 *(DynamicTerrainBase::*GetSFHeightDataScaleF)(void) const;

    GetSFHeightDataScaleF GetSFHeightDataScale = &DynamicTerrainBase::getSFHeightDataScale;
#endif

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "heightDataScale",
        "",
        HeightDataScaleFieldId, HeightDataScaleFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFHeightDataScale),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFHeightDataScale));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFHeightDataScale));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFReal32 *(DynamicTerrainBase::*GetSFHeightDataOffsetF)(void) const;

    GetSFHeightDataOffsetF GetSFHeightDataOffset = &DynamicTerrainBase::getSFHeightDataOffset;
#endif

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "heightDataOffset",
        "",
        HeightDataOffsetFieldId, HeightDataOffsetFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFHeightDataOffset),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFHeightDataOffset));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFHeightDataOffset));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFReal32 *(DynamicTerrainBase::*GetSFSampleDistanceF)(void) const;

    GetSFSampleDistanceF GetSFSampleDistance = &DynamicTerrainBase::getSFSampleDistance;
#endif

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "sampleDistance",
        "",
        SampleDistanceFieldId, SampleDistanceFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFSampleDistance),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFSampleDistance));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFSampleDistance));
#endif

    oType.addInitialDesc(pDesc);

    pDesc = new SFImagePtr::Description(
        SFImagePtr::getClassType(),
        "textureData",
        "",
        TextureDataFieldId, TextureDataFieldMask,
        false,
        Field::SFDefaultFlags,
        static_cast     <FieldEditMethodSig>(&DynamicTerrainBase::invalidEditField),
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFTextureData));

    oType.addInitialDesc(pDesc);

    pDesc = new SFTextureChunkPtr::Description(
        SFTextureChunkPtr::getClassType(),
        "heightColorTexture",
        "",
        HeightColorTextureFieldId, HeightColorTextureFieldMask,
        false,
        Field::SFDefaultFlags,
        static_cast     <FieldEditMethodSig>(&DynamicTerrainBase::invalidEditField),
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFHeightColorTexture));

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFInt32 *(DynamicTerrainBase::*GetSFSampleUpdateBudgetF)(void) const;

    GetSFSampleUpdateBudgetF GetSFSampleUpdateBudget = &DynamicTerrainBase::getSFSampleUpdateBudget;
#endif

    pDesc = new SFInt32::Description(
        SFInt32::getClassType(),
        "sampleUpdateBudget",
        "",
        SampleUpdateBudgetFieldId, SampleUpdateBudgetFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFSampleUpdateBudget),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFSampleUpdateBudget));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFSampleUpdateBudget));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFBool *(DynamicTerrainBase::*GetSFEnableFrustumCullingF)(void) const;

    GetSFEnableFrustumCullingF GetSFEnableFrustumCulling = &DynamicTerrainBase::getSFEnableFrustumCulling;
#endif

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "enableFrustumCulling",
        "",
        EnableFrustumCullingFieldId, EnableFrustumCullingFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFEnableFrustumCulling),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFEnableFrustumCulling));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFEnableFrustumCulling));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFBool *(DynamicTerrainBase::*GetSFUseGpuRendererF)(void) const;

    GetSFUseGpuRendererF GetSFUseGpuRenderer = &DynamicTerrainBase::getSFUseGpuRenderer;
#endif

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "useGpuRenderer",
        "",
        UseGpuRendererFieldId, UseGpuRendererFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFUseGpuRenderer),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFUseGpuRenderer));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFUseGpuRenderer));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFBool *(DynamicTerrainBase::*GetSFUseVboExtensionF)(void) const;

    GetSFUseVboExtensionF GetSFUseVboExtension = &DynamicTerrainBase::getSFUseVboExtension;
#endif

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "useVboExtension",
        "",
        UseVboExtensionFieldId, UseVboExtensionFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFUseVboExtension),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFUseVboExtension));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFUseVboExtension));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFBool *(DynamicTerrainBase::*GetSFEnableSmoothTransitionF)(void) const;

    GetSFEnableSmoothTransitionF GetSFEnableSmoothTransition = &DynamicTerrainBase::getSFEnableSmoothTransition;
#endif

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "enableSmoothTransition",
        "",
        EnableSmoothTransitionFieldId, EnableSmoothTransitionFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFEnableSmoothTransition),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFEnableSmoothTransition));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFEnableSmoothTransition));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFBool *(DynamicTerrainBase::*GetSFShowBoundingBoxesF)(void) const;

    GetSFShowBoundingBoxesF GetSFShowBoundingBoxes = &DynamicTerrainBase::getSFShowBoundingBoxes;
#endif

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "showBoundingBoxes",
        "",
        ShowBoundingBoxesFieldId, ShowBoundingBoxesFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFShowBoundingBoxes),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFShowBoundingBoxes));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFShowBoundingBoxes));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFBool *(DynamicTerrainBase::*GetSFShowTransitionRegionsF)(void) const;

    GetSFShowTransitionRegionsF GetSFShowTransitionRegions = &DynamicTerrainBase::getSFShowTransitionRegions;
#endif

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "showTransitionRegions",
        "",
        ShowTransitionRegionsFieldId, ShowTransitionRegionsFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFShowTransitionRegions),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFShowTransitionRegions));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFShowTransitionRegions));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFBool *(DynamicTerrainBase::*GetSFDisableUpdateF)(void) const;

    GetSFDisableUpdateF GetSFDisableUpdate = &DynamicTerrainBase::getSFDisableUpdate;
#endif

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "disableUpdate",
        "",
        DisableUpdateFieldId, DisableUpdateFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFDisableUpdate),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFDisableUpdate));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFDisableUpdate));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFString *(DynamicTerrainBase::*GetSFCpuVertexProgramF)(void) const;

    GetSFCpuVertexProgramF GetSFCpuVertexProgram = &DynamicTerrainBase::getSFCpuVertexProgram;
#endif

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "cpuVertexProgram",
        "",
        CpuVertexProgramFieldId, CpuVertexProgramFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFCpuVertexProgram),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFCpuVertexProgram));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFCpuVertexProgram));
#endif

    oType.addInitialDesc(pDesc);

#ifdef OSG_1_COMPAT
    typedef const SFString *(DynamicTerrainBase::*GetSFCpuFragmentProgramF)(void) const;

    GetSFCpuFragmentProgramF GetSFCpuFragmentProgram = &DynamicTerrainBase::getSFCpuFragmentProgram;
#endif

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "cpuFragmentProgram",
        "",
        CpuFragmentProgramFieldId, CpuFragmentProgramFieldMask,
        false,
        Field::SFDefaultFlags,
        reinterpret_cast<FieldEditMethodSig>(&DynamicTerrainBase::editSFCpuFragmentProgram),
#ifdef OSG_1_COMPAT
        reinterpret_cast<FieldGetMethodSig >(GetSFCpuFragmentProgram));
#else
        reinterpret_cast<FieldGetMethodSig >(&DynamicTerrainBase::getSFCpuFragmentProgram));
#endif

    oType.addInitialDesc(pDesc);
}


DynamicTerrainBase::TypeObject DynamicTerrainBase::_type(true,
    DynamicTerrainBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    (PrototypeCreateF) &DynamicTerrainBase::createEmpty,
    DynamicTerrain::initMethod,
    (InitalInsertDescFunc) &DynamicTerrainBase::classDescInserter,
    false,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"DynamicTerrain\"\n"
    "\tparent=\"MaterialDrawable\"\n"
    "\tpointerfieldtypes=\"none\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"true\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    ">\n"
    "  <Field\n"
    "\t\tname=\"levelSize\"\n"
    "\t\ttype=\"Int32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"63\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"heightData\"\n"
    "\t\ttype=\"ImagePtr\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"heightDataScale\"\n"
    "\t\ttype=\"Real32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"1.0\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"heightDataOffset\"\n"
    "\t\ttype=\"Real32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"0\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"sampleDistance\"\n"
    "\t\ttype=\"Real32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"1.0\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"textureData\"\n"
    "\t\ttype=\"ImagePtr\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "  </Field>  \n"
    "  <Field\n"
    "\t\tname=\"heightColorTexture\"\n"
    "\t\ttype=\"TextureChunkPtr\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"sampleUpdateBudget\"\n"
    "\t\ttype=\"Int32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"enableFrustumCulling\"\n"
    "\t\ttype=\"bool\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"useGpuRenderer\"\n"
    "\t\ttype=\"bool\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"false\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"useVboExtension\"\n"
    "\t\ttype=\"bool\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"true\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"enableSmoothTransition\"\n"
    "\t\ttype=\"bool\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"showBoundingBoxes\"\n"
    "\t\ttype=\"bool\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"showTransitionRegions\"\n"
    "\t\ttype=\"bool\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"false\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"disableUpdate\"\n"
    "\t\ttype=\"bool\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"false\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"cpuVertexProgram\"\n"
    "\t\ttype=\"std::string\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"\"\n"
    "\t>\n"
    "  </Field>\n"
    "  <Field\n"
    "\t\tname=\"cpuFragmentProgram\"\n"
    "\t\ttype=\"std::string\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "    defaultValue=\"\"\n"
    "\t>\n"
    "  </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &DynamicTerrainBase::getType(void)
{
    return _type;
}

const FieldContainerType &DynamicTerrainBase::getType(void) const
{
    return _type;
}

UInt32 DynamicTerrainBase::getContainerSize(void) const
{
    return sizeof(DynamicTerrain);
}

/*------------------------- decorator get ------------------------------*/


SFInt32 *DynamicTerrainBase::editSFLevelSize(void)
{
    editSField(LevelSizeFieldMask);

    return &_sfLevelSize;
}

const SFInt32 *DynamicTerrainBase::getSFLevelSize(void) const
{
    return &_sfLevelSize;
}

#ifdef OSG_1_COMPAT
SFInt32             *DynamicTerrainBase::getSFLevelSize      (void)
{
    return this->editSFLevelSize      ();
}
#endif

//! Get the DynamicTerrain::_sfHeightData field.
const SFImagePtr *DynamicTerrainBase::getSFHeightData(void) const
{
    return &_sfHeightData;
}

SFReal32 *DynamicTerrainBase::editSFHeightDataScale(void)
{
    editSField(HeightDataScaleFieldMask);

    return &_sfHeightDataScale;
}

const SFReal32 *DynamicTerrainBase::getSFHeightDataScale(void) const
{
    return &_sfHeightDataScale;
}

#ifdef OSG_1_COMPAT
SFReal32            *DynamicTerrainBase::getSFHeightDataScale(void)
{
    return this->editSFHeightDataScale();
}
#endif

SFReal32 *DynamicTerrainBase::editSFHeightDataOffset(void)
{
    editSField(HeightDataOffsetFieldMask);

    return &_sfHeightDataOffset;
}

const SFReal32 *DynamicTerrainBase::getSFHeightDataOffset(void) const
{
    return &_sfHeightDataOffset;
}

#ifdef OSG_1_COMPAT
SFReal32            *DynamicTerrainBase::getSFHeightDataOffset(void)
{
    return this->editSFHeightDataOffset();
}
#endif

SFReal32 *DynamicTerrainBase::editSFSampleDistance(void)
{
    editSField(SampleDistanceFieldMask);

    return &_sfSampleDistance;
}

const SFReal32 *DynamicTerrainBase::getSFSampleDistance(void) const
{
    return &_sfSampleDistance;
}

#ifdef OSG_1_COMPAT
SFReal32            *DynamicTerrainBase::getSFSampleDistance (void)
{
    return this->editSFSampleDistance ();
}
#endif

//! Get the DynamicTerrain::_sfTextureData field.
const SFImagePtr *DynamicTerrainBase::getSFTextureData(void) const
{
    return &_sfTextureData;
}

//! Get the DynamicTerrain::_sfHeightColorTexture field.
const SFTextureChunkPtr *DynamicTerrainBase::getSFHeightColorTexture(void) const
{
    return &_sfHeightColorTexture;
}

SFInt32 *DynamicTerrainBase::editSFSampleUpdateBudget(void)
{
    editSField(SampleUpdateBudgetFieldMask);

    return &_sfSampleUpdateBudget;
}

const SFInt32 *DynamicTerrainBase::getSFSampleUpdateBudget(void) const
{
    return &_sfSampleUpdateBudget;
}

#ifdef OSG_1_COMPAT
SFInt32             *DynamicTerrainBase::getSFSampleUpdateBudget(void)
{
    return this->editSFSampleUpdateBudget();
}
#endif

SFBool *DynamicTerrainBase::editSFEnableFrustumCulling(void)
{
    editSField(EnableFrustumCullingFieldMask);

    return &_sfEnableFrustumCulling;
}

const SFBool *DynamicTerrainBase::getSFEnableFrustumCulling(void) const
{
    return &_sfEnableFrustumCulling;
}

#ifdef OSG_1_COMPAT
SFBool              *DynamicTerrainBase::getSFEnableFrustumCulling(void)
{
    return this->editSFEnableFrustumCulling();
}
#endif

SFBool *DynamicTerrainBase::editSFUseGpuRenderer(void)
{
    editSField(UseGpuRendererFieldMask);

    return &_sfUseGpuRenderer;
}

const SFBool *DynamicTerrainBase::getSFUseGpuRenderer(void) const
{
    return &_sfUseGpuRenderer;
}

#ifdef OSG_1_COMPAT
SFBool              *DynamicTerrainBase::getSFUseGpuRenderer (void)
{
    return this->editSFUseGpuRenderer ();
}
#endif

SFBool *DynamicTerrainBase::editSFUseVboExtension(void)
{
    editSField(UseVboExtensionFieldMask);

    return &_sfUseVboExtension;
}

const SFBool *DynamicTerrainBase::getSFUseVboExtension(void) const
{
    return &_sfUseVboExtension;
}

#ifdef OSG_1_COMPAT
SFBool              *DynamicTerrainBase::getSFUseVboExtension(void)
{
    return this->editSFUseVboExtension();
}
#endif

SFBool *DynamicTerrainBase::editSFEnableSmoothTransition(void)
{
    editSField(EnableSmoothTransitionFieldMask);

    return &_sfEnableSmoothTransition;
}

const SFBool *DynamicTerrainBase::getSFEnableSmoothTransition(void) const
{
    return &_sfEnableSmoothTransition;
}

#ifdef OSG_1_COMPAT
SFBool              *DynamicTerrainBase::getSFEnableSmoothTransition(void)
{
    return this->editSFEnableSmoothTransition();
}
#endif

SFBool *DynamicTerrainBase::editSFShowBoundingBoxes(void)
{
    editSField(ShowBoundingBoxesFieldMask);

    return &_sfShowBoundingBoxes;
}

const SFBool *DynamicTerrainBase::getSFShowBoundingBoxes(void) const
{
    return &_sfShowBoundingBoxes;
}

#ifdef OSG_1_COMPAT
SFBool              *DynamicTerrainBase::getSFShowBoundingBoxes(void)
{
    return this->editSFShowBoundingBoxes();
}
#endif

SFBool *DynamicTerrainBase::editSFShowTransitionRegions(void)
{
    editSField(ShowTransitionRegionsFieldMask);

    return &_sfShowTransitionRegions;
}

const SFBool *DynamicTerrainBase::getSFShowTransitionRegions(void) const
{
    return &_sfShowTransitionRegions;
}

#ifdef OSG_1_COMPAT
SFBool              *DynamicTerrainBase::getSFShowTransitionRegions(void)
{
    return this->editSFShowTransitionRegions();
}
#endif

SFBool *DynamicTerrainBase::editSFDisableUpdate(void)
{
    editSField(DisableUpdateFieldMask);

    return &_sfDisableUpdate;
}

const SFBool *DynamicTerrainBase::getSFDisableUpdate(void) const
{
    return &_sfDisableUpdate;
}

#ifdef OSG_1_COMPAT
SFBool              *DynamicTerrainBase::getSFDisableUpdate  (void)
{
    return this->editSFDisableUpdate  ();
}
#endif

SFString *DynamicTerrainBase::editSFCpuVertexProgram(void)
{
    editSField(CpuVertexProgramFieldMask);

    return &_sfCpuVertexProgram;
}

const SFString *DynamicTerrainBase::getSFCpuVertexProgram(void) const
{
    return &_sfCpuVertexProgram;
}

#ifdef OSG_1_COMPAT
SFString            *DynamicTerrainBase::getSFCpuVertexProgram(void)
{
    return this->editSFCpuVertexProgram();
}
#endif

SFString *DynamicTerrainBase::editSFCpuFragmentProgram(void)
{
    editSField(CpuFragmentProgramFieldMask);

    return &_sfCpuFragmentProgram;
}

const SFString *DynamicTerrainBase::getSFCpuFragmentProgram(void) const
{
    return &_sfCpuFragmentProgram;
}

#ifdef OSG_1_COMPAT
SFString            *DynamicTerrainBase::getSFCpuFragmentProgram(void)
{
    return this->editSFCpuFragmentProgram();
}
#endif


void DynamicTerrainBase::pushToField(      FieldContainerPtrConstArg pNewElement,
                                    const UInt32                    uiFieldId  )
{
    Inherited::pushToField(pNewElement, uiFieldId);

    if(uiFieldId == HeightDataFieldId)
    {
        static_cast<DynamicTerrain *>(this)->setHeightData(
            cast_dynamic<ImagePtr>(pNewElement));
    }
    if(uiFieldId == TextureDataFieldId)
    {
        static_cast<DynamicTerrain *>(this)->setTextureData(
            cast_dynamic<ImagePtr>(pNewElement));
    }
    if(uiFieldId == HeightColorTextureFieldId)
    {
        static_cast<DynamicTerrain *>(this)->setHeightColorTexture(
            cast_dynamic<TextureChunkPtr>(pNewElement));
    }
}

void DynamicTerrainBase::insertIntoMField(const UInt32                    uiIndex,
                                               FieldContainerPtrConstArg pNewElement,
                                         const UInt32                    uiFieldId  )
{
    Inherited::insertIntoMField(uiIndex, pNewElement, uiFieldId);

}

void DynamicTerrainBase::replaceInMField (const UInt32                    uiIndex,
                                               FieldContainerPtrConstArg pNewElement,
                                         const UInt32                    uiFieldId)
{
    Inherited::replaceInMField(uiIndex, pNewElement, uiFieldId);

}

void DynamicTerrainBase::replaceInMField (      FieldContainerPtrConstArg pOldElement,
                                               FieldContainerPtrConstArg pNewElement,
                                         const UInt32                    uiFieldId  )
{
    Inherited::replaceInMField(pOldElement, pNewElement, uiFieldId);

}

void DynamicTerrainBase::removeFromMField(const UInt32 uiIndex,
                                         const UInt32 uiFieldId)
{
    Inherited::removeFromMField(uiIndex, uiFieldId);

}

void DynamicTerrainBase::removeFromMField(      FieldContainerPtrConstArg pElement,
                                         const UInt32                    uiFieldId)
{
    Inherited::removeFromMField(pElement, uiFieldId);

}

void DynamicTerrainBase::clearField(const UInt32 uiFieldId)
{
    Inherited::clearField(uiFieldId);

    if(uiFieldId == HeightDataFieldId)
    {
        static_cast<DynamicTerrain *>(this)->setHeightData(NullFC);
    }
    if(uiFieldId == TextureDataFieldId)
    {
        static_cast<DynamicTerrain *>(this)->setTextureData(NullFC);
    }
    if(uiFieldId == HeightColorTextureFieldId)
    {
        static_cast<DynamicTerrain *>(this)->setHeightColorTexture(NullFC);
    }
}



/*------------------------------ access -----------------------------------*/

UInt32 DynamicTerrainBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (LevelSizeFieldMask & whichField))
    {
        returnValue += _sfLevelSize.getBinSize();
    }
    if(FieldBits::NoField != (HeightDataFieldMask & whichField))
    {
        returnValue += _sfHeightData.getBinSize();
    }
    if(FieldBits::NoField != (HeightDataScaleFieldMask & whichField))
    {
        returnValue += _sfHeightDataScale.getBinSize();
    }
    if(FieldBits::NoField != (HeightDataOffsetFieldMask & whichField))
    {
        returnValue += _sfHeightDataOffset.getBinSize();
    }
    if(FieldBits::NoField != (SampleDistanceFieldMask & whichField))
    {
        returnValue += _sfSampleDistance.getBinSize();
    }
    if(FieldBits::NoField != (TextureDataFieldMask & whichField))
    {
        returnValue += _sfTextureData.getBinSize();
    }
    if(FieldBits::NoField != (HeightColorTextureFieldMask & whichField))
    {
        returnValue += _sfHeightColorTexture.getBinSize();
    }
    if(FieldBits::NoField != (SampleUpdateBudgetFieldMask & whichField))
    {
        returnValue += _sfSampleUpdateBudget.getBinSize();
    }
    if(FieldBits::NoField != (EnableFrustumCullingFieldMask & whichField))
    {
        returnValue += _sfEnableFrustumCulling.getBinSize();
    }
    if(FieldBits::NoField != (UseGpuRendererFieldMask & whichField))
    {
        returnValue += _sfUseGpuRenderer.getBinSize();
    }
    if(FieldBits::NoField != (UseVboExtensionFieldMask & whichField))
    {
        returnValue += _sfUseVboExtension.getBinSize();
    }
    if(FieldBits::NoField != (EnableSmoothTransitionFieldMask & whichField))
    {
        returnValue += _sfEnableSmoothTransition.getBinSize();
    }
    if(FieldBits::NoField != (ShowBoundingBoxesFieldMask & whichField))
    {
        returnValue += _sfShowBoundingBoxes.getBinSize();
    }
    if(FieldBits::NoField != (ShowTransitionRegionsFieldMask & whichField))
    {
        returnValue += _sfShowTransitionRegions.getBinSize();
    }
    if(FieldBits::NoField != (DisableUpdateFieldMask & whichField))
    {
        returnValue += _sfDisableUpdate.getBinSize();
    }
    if(FieldBits::NoField != (CpuVertexProgramFieldMask & whichField))
    {
        returnValue += _sfCpuVertexProgram.getBinSize();
    }
    if(FieldBits::NoField != (CpuFragmentProgramFieldMask & whichField))
    {
        returnValue += _sfCpuFragmentProgram.getBinSize();
    }

    return returnValue;
}

void DynamicTerrainBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (LevelSizeFieldMask & whichField))
    {
        _sfLevelSize.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataFieldMask & whichField))
    {
        _sfHeightData.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataScaleFieldMask & whichField))
    {
        _sfHeightDataScale.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataOffsetFieldMask & whichField))
    {
        _sfHeightDataOffset.copyToBin(pMem);
    }
    if(FieldBits::NoField != (SampleDistanceFieldMask & whichField))
    {
        _sfSampleDistance.copyToBin(pMem);
    }
    if(FieldBits::NoField != (TextureDataFieldMask & whichField))
    {
        _sfTextureData.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightColorTextureFieldMask & whichField))
    {
        _sfHeightColorTexture.copyToBin(pMem);
    }
    if(FieldBits::NoField != (SampleUpdateBudgetFieldMask & whichField))
    {
        _sfSampleUpdateBudget.copyToBin(pMem);
    }
    if(FieldBits::NoField != (EnableFrustumCullingFieldMask & whichField))
    {
        _sfEnableFrustumCulling.copyToBin(pMem);
    }
    if(FieldBits::NoField != (UseGpuRendererFieldMask & whichField))
    {
        _sfUseGpuRenderer.copyToBin(pMem);
    }
    if(FieldBits::NoField != (UseVboExtensionFieldMask & whichField))
    {
        _sfUseVboExtension.copyToBin(pMem);
    }
    if(FieldBits::NoField != (EnableSmoothTransitionFieldMask & whichField))
    {
        _sfEnableSmoothTransition.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ShowBoundingBoxesFieldMask & whichField))
    {
        _sfShowBoundingBoxes.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ShowTransitionRegionsFieldMask & whichField))
    {
        _sfShowTransitionRegions.copyToBin(pMem);
    }
    if(FieldBits::NoField != (DisableUpdateFieldMask & whichField))
    {
        _sfDisableUpdate.copyToBin(pMem);
    }
    if(FieldBits::NoField != (CpuVertexProgramFieldMask & whichField))
    {
        _sfCpuVertexProgram.copyToBin(pMem);
    }
    if(FieldBits::NoField != (CpuFragmentProgramFieldMask & whichField))
    {
        _sfCpuFragmentProgram.copyToBin(pMem);
    }
}

void DynamicTerrainBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (LevelSizeFieldMask & whichField))
    {
        _sfLevelSize.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataFieldMask & whichField))
    {
        _sfHeightData.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataScaleFieldMask & whichField))
    {
        _sfHeightDataScale.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataOffsetFieldMask & whichField))
    {
        _sfHeightDataOffset.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (SampleDistanceFieldMask & whichField))
    {
        _sfSampleDistance.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (TextureDataFieldMask & whichField))
    {
        _sfTextureData.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightColorTextureFieldMask & whichField))
    {
        _sfHeightColorTexture.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (SampleUpdateBudgetFieldMask & whichField))
    {
        _sfSampleUpdateBudget.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (EnableFrustumCullingFieldMask & whichField))
    {
        _sfEnableFrustumCulling.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (UseGpuRendererFieldMask & whichField))
    {
        _sfUseGpuRenderer.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (UseVboExtensionFieldMask & whichField))
    {
        _sfUseVboExtension.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (EnableSmoothTransitionFieldMask & whichField))
    {
        _sfEnableSmoothTransition.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ShowBoundingBoxesFieldMask & whichField))
    {
        _sfShowBoundingBoxes.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ShowTransitionRegionsFieldMask & whichField))
    {
        _sfShowTransitionRegions.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (DisableUpdateFieldMask & whichField))
    {
        _sfDisableUpdate.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (CpuVertexProgramFieldMask & whichField))
    {
        _sfCpuVertexProgram.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (CpuFragmentProgramFieldMask & whichField))
    {
        _sfCpuFragmentProgram.copyFromBin(pMem);
    }
}

//! create an empty new instance of the class, do not copy the prototype
DynamicTerrainPtr DynamicTerrainBase::createEmpty(void)
{
    DynamicTerrainPtr returnValue;

    newPtr<DynamicTerrain>(returnValue);

    return returnValue;
}

FieldContainerPtr DynamicTerrainBase::shallowCopy(void) const
{
    DynamicTerrainPtr returnValue;

    newPtr(returnValue, dynamic_cast<const DynamicTerrain *>(this));

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

DynamicTerrainBase::DynamicTerrainBase(void) :
    Inherited(),
    _sfLevelSize              (Int32(63)),
    _sfHeightData             (),
    _sfHeightDataScale        (Real32(1.0)),
    _sfHeightDataOffset       (Real32(0)),
    _sfSampleDistance         (Real32(1.0)),
    _sfTextureData            (),
    _sfHeightColorTexture     (),
    _sfSampleUpdateBudget     (),
    _sfEnableFrustumCulling   (),
    _sfUseGpuRenderer         (bool(false)),
    _sfUseVboExtension        (bool(true)),
    _sfEnableSmoothTransition (),
    _sfShowBoundingBoxes      (),
    _sfShowTransitionRegions  (bool(false)),
    _sfDisableUpdate          (bool(false)),
    _sfCpuVertexProgram       (),
    _sfCpuFragmentProgram     ()
{
}

DynamicTerrainBase::DynamicTerrainBase(const DynamicTerrainBase &source) :
    Inherited(source),
    _sfLevelSize              (source._sfLevelSize              ),
    _sfHeightData             (),
    _sfHeightDataScale        (source._sfHeightDataScale        ),
    _sfHeightDataOffset       (source._sfHeightDataOffset       ),
    _sfSampleDistance         (source._sfSampleDistance         ),
    _sfTextureData            (),
    _sfHeightColorTexture     (),
    _sfSampleUpdateBudget     (source._sfSampleUpdateBudget     ),
    _sfEnableFrustumCulling   (source._sfEnableFrustumCulling   ),
    _sfUseGpuRenderer         (source._sfUseGpuRenderer         ),
    _sfUseVboExtension        (source._sfUseVboExtension        ),
    _sfEnableSmoothTransition (source._sfEnableSmoothTransition ),
    _sfShowBoundingBoxes      (source._sfShowBoundingBoxes      ),
    _sfShowTransitionRegions  (source._sfShowTransitionRegions  ),
    _sfDisableUpdate          (source._sfDisableUpdate          ),
    _sfCpuVertexProgram       (source._sfCpuVertexProgram       ),
    _sfCpuFragmentProgram     (source._sfCpuFragmentProgram     )
{
}

/*-------------------------- destructors ----------------------------------*/

DynamicTerrainBase::~DynamicTerrainBase(void)
{
}

void DynamicTerrainBase::onCreate(const DynamicTerrain *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {

        this->setHeightData(source->getHeightData());

        this->setTextureData(source->getTextureData());

        this->setHeightColorTexture(source->getHeightColorTexture());
    }
}

#ifdef OSG_MT_FIELDCONTAINERPTR
void DynamicTerrainBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo,
                                        UInt32             uiCopyOffset)
{
    this->execSync(static_cast<DynamicTerrainBase *>(&oFrom),
                   whichField,
                   syncMode,
                   uiSyncInfo,
                   uiCopyOffset);
}
#endif

#ifdef OSG_MT_CPTR_ASPECT
void DynamicTerrainBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    this->execSync(static_cast<DynamicTerrainBase *>(&oFrom),
                   whichField,
                   oOffsets,
                   syncMode,
                   uiSyncInfo);
}
#endif

#if 0
void DynamicTerrainBase::execBeginEditV(ConstFieldMaskArg whichField,
                                       UInt32            uiAspect,
                                       UInt32            uiContainerSize)
{
    this->execBeginEdit(whichField, uiAspect, uiContainerSize);
}
#endif

#ifdef OSG_MT_CPTR_ASPECT
FieldContainerPtr DynamicTerrainBase::createAspectCopy(void) const
{
    DynamicTerrainPtr returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const DynamicTerrain *>(this));

    return returnValue;
}
#endif

void DynamicTerrainBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<DynamicTerrain *>(this)->setHeightData(NullFC);

    static_cast<DynamicTerrain *>(this)->setTextureData(NullFC);

    static_cast<DynamicTerrain *>(this)->setHeightColorTexture(NullFC);
}


#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<DynamicTerrainPtr>::_type("DynamicTerrainPtr", "MaterialDrawablePtr");
#endif


OSG_END_NAMESPACE
