/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSCRIPTFIELDS_H_
#define _OSGSCRIPTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGScriptingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class Script;

OSG_GEN_CONTAINERPTR(Script);
/*! \ingroup GrpScriptingFieldTraits
    \ingroup GrpLibOSGScripting
 */
template <>
struct FieldTraits<Script *, nsOSG> :
    public FieldTraitsFCPtrBase<Script *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<Script *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SCRIPTING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<Script *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdScriptPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<Script *,
                      RecordedRefCountPolicy, nsOSG  > SFRecScriptPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<Script *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecScriptPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<Script *,
                      WeakRefCountPolicy, nsOSG      > SFWeakScriptPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<Script *,
                      NoRefCountPolicy, nsOSG        > SFUncountedScriptPtr;


/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<Script *,
                      RecordedRefCountPolicy, nsOSG  > MFRecScriptPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<Script *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecScriptPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<Script *,
                      WeakRefCountPolicy, nsOSG      > MFWeakScriptPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<Script *,
                      NoRefCountPolicy, nsOSG        > MFUncountedScriptPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFRecScriptPtr : 
    public PointerSField<Script *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUnrecScriptPtr : 
    public PointerSField<Script *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFWeakScriptPtr :
    public PointerSField<Script *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUncountedScriptPtr :
    public PointerSField<Script *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFRecScriptPtr :
    public PointerMField<Script *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUnrecScriptPtr :
    public PointerMField<Script *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFWeakScriptPtr :
    public PointerMField<Script *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUncountedScriptPtr :
    public PointerMField<Script *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSCRIPTFIELDS_H_ */
