/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTRIPSSOUNDFIELDS_H_
#define _OSGTRIPSSOUNDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGTRIPSDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TRIPSSound;

OSG_GEN_CONTAINERPTR(TRIPSSound);
/*! \ingroup GrpTRIPSFieldTraits
    \ingroup GrpLibOSGTRIPS
 */
template <>
struct FieldTraits<TRIPSSound *, nsOSG> :
    public FieldTraitsFCPtrBase<TRIPSSound *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TRIPSSound *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_TRIPS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTRIPSSoundPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTRIPSSoundPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTRIPSSoundPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTRIPSSoundPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTRIPSSoundPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTRIPSSoundPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTRIPSSoundPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSSound *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTRIPSSoundPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSSound *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTRIPSSoundPtr;
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSSound *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTRIPSSoundPtr;
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSSound *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTRIPSSoundPtr;
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSSound *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTRIPSSoundPtr;


/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSSound *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTRIPSSoundPtr;
/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSSound *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTRIPSSoundPtr;
/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSSound *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTRIPSSoundPtr;
/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSSound *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTRIPSSoundPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFRecTRIPSSoundPtr : 
    public PointerSField<TRIPSSound *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFUnrecTRIPSSoundPtr : 
    public PointerSField<TRIPSSound *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFWeakTRIPSSoundPtr :
    public PointerSField<TRIPSSound *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFUncountedTRIPSSoundPtr :
    public PointerSField<TRIPSSound *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFRecTRIPSSoundPtr :
    public PointerMField<TRIPSSound *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFUnrecTRIPSSoundPtr :
    public PointerMField<TRIPSSound *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFWeakTRIPSSoundPtr :
    public PointerMField<TRIPSSound *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFUncountedTRIPSSoundPtr :
    public PointerMField<TRIPSSound *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTRIPSSOUNDFIELDS_H_ */
