MACRO(OSG_CONFIGURE_SOFA)

  OSG_FIND_PACKAGE(SOFA)

  IF(SOFA_FOUND)
    MESSAGE("FOOOO ${SOFA_LIB_LIST}")

    SET(SOFA_LIBRARIES "" CACHE STRING "" FORCE)

    FOREACH(SOFA_LIB ${SOFA_LIB_LIST})
      STRING(TOUPPER ${SOFA_LIB} SOFA_LIB_UC)

      OSG_ADD_IMPORT_LIB(OSG_${SOFA_LIB_UC}_TARGETS ${SOFA_LIB_UC}_LIBRARY)

#	  LIST(APPEND SOFA_LIBRARIES ${OSG_${SOFA_LIB_UC}_TARGETS})

	  SET(SOFA_LIBRARIES ${SOFA_LIBRARIES} ${OSG_${SOFA_LIB_UC}_TARGETS}
                         CACHE STRING "" FORCE)

      OSG_ADD_OPT(OSG_${SOFA_LIB_UC}_TARGETS)
	ENDFOREACH()

	OSG_SET(OSG_WITH_SOFA 1)

  ENDIF(SOFA_FOUND)

ENDMACRO(OSG_CONFIGURE_SOFA)
