/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSIMPLECUDACOMPUTEALGORITHMFIELDS_H_
#define _OSGSIMPLECUDACOMPUTEALGORITHMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribComputeDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class SimpleCudaComputeAlgorithm;

OSG_GEN_CONTAINERPTR(SimpleCudaComputeAlgorithm);

/*! \ingroup GrpContribComputeFieldTraits
    \ingroup GrpLibOSGContribCompute
 */
template <>
struct FieldTraits<SimpleCudaComputeAlgorithm *> :
    public FieldTraitsFCPtrBase<SimpleCudaComputeAlgorithm *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SimpleCudaComputeAlgorithm *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBCOMPUTE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSimpleCudaComputeAlgorithmPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSimpleCudaComputeAlgorithmPtr"; }
};

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSimpleCudaComputeAlgorithmPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSimpleCudaComputeAlgorithmPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSimpleCudaComputeAlgorithmPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSimpleCudaComputeAlgorithmPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSimpleCudaComputeAlgorithmPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSimpleCudaComputeAlgorithmPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSimpleCudaComputeAlgorithmPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleCudaComputeAlgorithm *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSimpleCudaComputeAlgorithmPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribComputeFieldSFields */
typedef PointerSField<SimpleCudaComputeAlgorithm *,
                      RecordedRefCountPolicy  > SFRecSimpleCudaComputeAlgorithmPtr;
/*! \ingroup GrpContribComputeFieldSFields */
typedef PointerSField<SimpleCudaComputeAlgorithm *,
                      UnrecordedRefCountPolicy> SFUnrecSimpleCudaComputeAlgorithmPtr;
/*! \ingroup GrpContribComputeFieldSFields */
typedef PointerSField<SimpleCudaComputeAlgorithm *,
                      WeakRefCountPolicy      > SFWeakSimpleCudaComputeAlgorithmPtr;
/*! \ingroup GrpContribComputeFieldSFields */
typedef PointerSField<SimpleCudaComputeAlgorithm *,
                      NoRefCountPolicy        > SFUncountedSimpleCudaComputeAlgorithmPtr;


/*! \ingroup GrpContribComputeFieldMFields */
typedef PointerMField<SimpleCudaComputeAlgorithm *,
                      RecordedRefCountPolicy  > MFRecSimpleCudaComputeAlgorithmPtr;
/*! \ingroup GrpContribComputeFieldMFields */
typedef PointerMField<SimpleCudaComputeAlgorithm *,
                      UnrecordedRefCountPolicy> MFUnrecSimpleCudaComputeAlgorithmPtr;
/*! \ingroup GrpContribComputeFieldMFields */
typedef PointerMField<SimpleCudaComputeAlgorithm *,
                      WeakRefCountPolicy      > MFWeakSimpleCudaComputeAlgorithmPtr;
/*! \ingroup GrpContribComputeFieldMFields */
typedef PointerMField<SimpleCudaComputeAlgorithm *,
                      NoRefCountPolicy        > MFUncountedSimpleCudaComputeAlgorithmPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribComputeFieldSFields \ingroup GrpLibOSGContribCompute */
struct SFRecSimpleCudaComputeAlgorithmPtr : 
    public PointerSField<SimpleCudaComputeAlgorithm *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribComputeFieldSFields \ingroup GrpLibOSGContribCompute */
struct SFUnrecSimpleCudaComputeAlgorithmPtr : 
    public PointerSField<SimpleCudaComputeAlgorithm *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribComputeFieldSFields \ingroup GrpLibOSGContribCompute */
struct SFWeakSimpleCudaComputeAlgorithmPtr :
    public PointerSField<SimpleCudaComputeAlgorithm *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribComputeFieldSFields \ingroup GrpLibOSGContribCompute */
struct SFUncountedSimpleCudaComputeAlgorithmPtr :
    public PointerSField<SimpleCudaComputeAlgorithm *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribComputeFieldMFields \ingroup GrpLibOSGContribCompute */
struct MFRecSimpleCudaComputeAlgorithmPtr :
    public PointerMField<SimpleCudaComputeAlgorithm *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribComputeFieldMFields \ingroup GrpLibOSGContribCompute */
struct MFUnrecSimpleCudaComputeAlgorithmPtr :
    public PointerMField<SimpleCudaComputeAlgorithm *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribComputeFieldMFields \ingroup GrpLibOSGContribCompute */
struct MFWeakSimpleCudaComputeAlgorithmPtr :
    public PointerMField<SimpleCudaComputeAlgorithm *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribComputeFieldMFields \ingroup GrpLibOSGContribCompute */
struct MFUncountedSimpleCudaComputeAlgorithmPtr :
    public PointerMField<SimpleCudaComputeAlgorithm *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSIMPLECUDACOMPUTEALGORITHMFIELDS_H_ */
