/** Auto-generated temporary file for header containment. */
#include <PreBoostPython.h>
#include <pypp_aliases.h>
#include <OSGRenderAction.h>
#include <OSGStageParent.h>
#include <OSGFrameBufferObject.h>
#include <OSGTextureBuffer.h>
#include <OSGTextureObjChunk.h>
#include <OSGChunkMaterial.h>
#include <OSGTextureTransformChunk.h>
#include <OSGShaderProgram.h>
#include <OSGImage.h>
#include <OSGForeground.h>
#include <OSGBlendChunk.h>
#include <OSGPolygonChunk.h>
#include <OSGTexGenChunk.h>
#include <OSGCubeMapGeneratorStageData.h>
#include <OSGDynamicStateGenerator.h>
#include <OSGCubeMapGenerator.h>
#include <OSGDynamicStateGeneratorStageData.h>
#include <OSGDirectionalLight.h>
#include <OSGSpotLight.h>
#include <OSGPointLight.h>
#include <OSGShaderShadowMapEngine.h>
#include <OSGSimpleShadowMapEngineData.h>
#include <OSGShaderShadowMapEngineData.h>
#include <OSGVisitSubTree.h>
#include <OSGScreenGroup.h>
#include <OSGInline.h>
#include <OSGSwitch.h>
#include <OSGInverseTransform.h>
#include <OSGScreenTransform.h>
#include <OSGTransform.h>
#include <OSGRangeLOD.h>
#include <OSGProxyGroup.h>
#include <OSGStackedTransform.h>
#include <OSGComponentTransform.h>
#include <OSGBillboard.h>
#include <OSGScreenLOD.h>
#include <OSGMaterialChunkOverrideGroup.h>
#include <OSGDoubleTransform.h>
#include <OSGMultiSwitch.h>
#include <OSGDistanceLOD.h>
#include <OSGReplicateTransform.h>
#include <OSGRotationTransformationElement.h>
#include <OSGMatrixTransformationElement.h>
#include <OSGTransformationElement.h>
#include <OSGTranslationTransformationElement.h>
#include <OSGLookAtTransformationElement.h>
#include <OSGScaleTransformationElement.h>
#include <OSGSkewTransformationElement.h>
#include <OSGStage.h>
#include <OSGRenderCallbackStage.h>
#include <OSGSimpleStage.h>
#include <OSGStageData.h>
#include <OSGAlgorithmStage.h>
#include <OSGAlgorithm.h>
#include <OSGCallbackAlgorithm.h>
#include <OSGGroupingStage.h>

#if defined(Bool)
#undef Bool
#endif

/** Autogenerated temporary file for template instantiation. */

            typedef OSG::ContainerMixinHead<OSG::StageDesc> alias_StageContainerParent;
            inline unsigned __instantiate_alias_StageContainerParent()
            { return unsigned(sizeof(alias_StageContainerParent)); }
         
            typedef OSG::TraversalValidationHandlerMixin< OSG::ContainerMixinHead<OSG::StageDesc> > alias_StageParentBase;
            inline unsigned __instantiate_alias_StageParentBase()
            { return unsigned(sizeof(alias_StageParentBase)); }
         
            typedef OSG::StageParent alias_StageParent;
            inline unsigned __instantiate_alias_StageParent()
            { return unsigned(sizeof(alias_StageParent)); }
         

// Member template instantiations
#if defined(__GCCXML__)
#endif


