/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVLCVIDEOTEXTUREOBJCHUNKFIELDS_H_
#define _OSGVLCVIDEOTEXTUREOBJCHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGAddOnsConfig.h"
#include "OSGVLCVideoTextureDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class VLCVideoTextureObjChunk;

OSG_GEN_CONTAINERPTR(VLCVideoTextureObjChunk);
/*! \ingroup GrpVLCVideoTextureFieldTraits
    \ingroup GrpLibOSGVLCVideoTexture
 */
template <>
struct FieldTraits<VLCVideoTextureObjChunk *, nsOSG> :
    public FieldTraitsFCPtrBase<VLCVideoTextureObjChunk *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<VLCVideoTextureObjChunk *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VLCVIDEOTEXTURE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVLCVideoTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVLCVideoTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVLCVideoTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVLCVideoTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVLCVideoTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVLCVideoTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVLCVideoTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<VLCVideoTextureObjChunk *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVLCVideoTextureObjChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVLCVideoTextureFieldSFields */
typedef PointerSField<VLCVideoTextureObjChunk *,
                      RecordedRefCountPolicy, nsOSG  > SFRecVLCVideoTextureObjChunkPtr;
/*! \ingroup GrpVLCVideoTextureFieldSFields */
typedef PointerSField<VLCVideoTextureObjChunk *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecVLCVideoTextureObjChunkPtr;
/*! \ingroup GrpVLCVideoTextureFieldSFields */
typedef PointerSField<VLCVideoTextureObjChunk *,
                      WeakRefCountPolicy, nsOSG      > SFWeakVLCVideoTextureObjChunkPtr;
/*! \ingroup GrpVLCVideoTextureFieldSFields */
typedef PointerSField<VLCVideoTextureObjChunk *,
                      NoRefCountPolicy, nsOSG        > SFUncountedVLCVideoTextureObjChunkPtr;


/*! \ingroup GrpVLCVideoTextureFieldMFields */
typedef PointerMField<VLCVideoTextureObjChunk *,
                      RecordedRefCountPolicy, nsOSG  > MFRecVLCVideoTextureObjChunkPtr;
/*! \ingroup GrpVLCVideoTextureFieldMFields */
typedef PointerMField<VLCVideoTextureObjChunk *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecVLCVideoTextureObjChunkPtr;
/*! \ingroup GrpVLCVideoTextureFieldMFields */
typedef PointerMField<VLCVideoTextureObjChunk *,
                      WeakRefCountPolicy, nsOSG      > MFWeakVLCVideoTextureObjChunkPtr;
/*! \ingroup GrpVLCVideoTextureFieldMFields */
typedef PointerMField<VLCVideoTextureObjChunk *,
                      NoRefCountPolicy, nsOSG        > MFUncountedVLCVideoTextureObjChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVLCVideoTextureFieldSFields \ingroup GrpLibOSGVLCVideoTexture */
struct SFRecVLCVideoTextureObjChunkPtr : 
    public PointerSField<VLCVideoTextureObjChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVLCVideoTextureFieldSFields \ingroup GrpLibOSGVLCVideoTexture */
struct SFUnrecVLCVideoTextureObjChunkPtr : 
    public PointerSField<VLCVideoTextureObjChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVLCVideoTextureFieldSFields \ingroup GrpLibOSGVLCVideoTexture */
struct SFWeakVLCVideoTextureObjChunkPtr :
    public PointerSField<VLCVideoTextureObjChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVLCVideoTextureFieldSFields \ingroup GrpLibOSGVLCVideoTexture */
struct SFUncountedVLCVideoTextureObjChunkPtr :
    public PointerSField<VLCVideoTextureObjChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVLCVideoTextureFieldMFields \ingroup GrpLibOSGVLCVideoTexture */
struct MFRecVLCVideoTextureObjChunkPtr :
    public PointerMField<VLCVideoTextureObjChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVLCVideoTextureFieldMFields \ingroup GrpLibOSGVLCVideoTexture */
struct MFUnrecVLCVideoTextureObjChunkPtr :
    public PointerMField<VLCVideoTextureObjChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVLCVideoTextureFieldMFields \ingroup GrpLibOSGVLCVideoTexture */
struct MFWeakVLCVideoTextureObjChunkPtr :
    public PointerMField<VLCVideoTextureObjChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVLCVideoTextureFieldMFields \ingroup GrpLibOSGVLCVideoTexture */
struct MFUncountedVLCVideoTextureObjChunkPtr :
    public PointerMField<VLCVideoTextureObjChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVLCVIDEOTEXTUREOBJCHUNKFIELDS_H_ */
