/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPYFIELDCONTAINERPTRMFIELDGETHANDLEFIELDS_H_
#define _OSGPYFIELDCONTAINERPTRMFIELDGETHANDLEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGScriptingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class PyFieldContainerPtrMFieldGetHandle;

OSG_GEN_CONTAINERPTR(PyFieldContainerPtrMFieldGetHandle);
/*! \ingroup GrpScriptingFieldTraits
    \ingroup GrpLibOSGScripting
 */
template <>
struct FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG> :
    public FieldTraitsFCPtrBase<PyFieldContainerPtrMFieldGetHandle *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SCRIPTING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPyFieldContainerPtrMFieldGetHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPyFieldContainerPtrMFieldGetHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPyFieldContainerPtrMFieldGetHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPyFieldContainerPtrMFieldGetHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPyFieldContainerPtrMFieldGetHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPyFieldContainerPtrMFieldGetHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPyFieldContainerPtrMFieldGetHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPyFieldContainerPtrMFieldGetHandlePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                      RecordedRefCountPolicy, nsOSG  > SFRecPyFieldContainerPtrMFieldGetHandlePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecPyFieldContainerPtrMFieldGetHandlePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                      WeakRefCountPolicy, nsOSG      > SFWeakPyFieldContainerPtrMFieldGetHandlePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                      NoRefCountPolicy, nsOSG        > SFUncountedPyFieldContainerPtrMFieldGetHandlePtr;


/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                      RecordedRefCountPolicy, nsOSG  > MFRecPyFieldContainerPtrMFieldGetHandlePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecPyFieldContainerPtrMFieldGetHandlePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                      WeakRefCountPolicy, nsOSG      > MFWeakPyFieldContainerPtrMFieldGetHandlePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                      NoRefCountPolicy, nsOSG        > MFUncountedPyFieldContainerPtrMFieldGetHandlePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFRecPyFieldContainerPtrMFieldGetHandlePtr : 
    public PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUnrecPyFieldContainerPtrMFieldGetHandlePtr : 
    public PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFWeakPyFieldContainerPtrMFieldGetHandlePtr :
    public PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUncountedPyFieldContainerPtrMFieldGetHandlePtr :
    public PointerSField<PyFieldContainerPtrMFieldGetHandle *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFRecPyFieldContainerPtrMFieldGetHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUnrecPyFieldContainerPtrMFieldGetHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFWeakPyFieldContainerPtrMFieldGetHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUncountedPyFieldContainerPtrMFieldGetHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldGetHandle *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPYFIELDCONTAINERPTRMFIELDGETHANDLEFIELDS_H_ */
