/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPYFIELDCONTAINERPTRMFIELDEDITHANDLEFIELDS_H_
#define _OSGPYFIELDCONTAINERPTRMFIELDEDITHANDLEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGScriptingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PyFieldContainerPtrMFieldEditHandle;

OSG_GEN_CONTAINERPTR(PyFieldContainerPtrMFieldEditHandle);

/*! \ingroup GrpScriptingFieldTraits
    \ingroup GrpLibOSGScripting
 */
template <>
struct FieldTraits<PyFieldContainerPtrMFieldEditHandle *> :
    public FieldTraitsFCPtrBase<PyFieldContainerPtrMFieldEditHandle *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PyFieldContainerPtrMFieldEditHandle *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SCRIPTING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPyFieldContainerPtrMFieldEditHandlePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPyFieldContainerPtrMFieldEditHandlePtr"; }
};

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPyFieldContainerPtrMFieldEditHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPyFieldContainerPtrMFieldEditHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPyFieldContainerPtrMFieldEditHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPyFieldContainerPtrMFieldEditHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPyFieldContainerPtrMFieldEditHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPyFieldContainerPtrMFieldEditHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPyFieldContainerPtrMFieldEditHandlePtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldContainerPtrMFieldEditHandle *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPyFieldContainerPtrMFieldEditHandlePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                      RecordedRefCountPolicy  > SFRecPyFieldContainerPtrMFieldEditHandlePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                      UnrecordedRefCountPolicy> SFUnrecPyFieldContainerPtrMFieldEditHandlePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                      WeakRefCountPolicy      > SFWeakPyFieldContainerPtrMFieldEditHandlePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                      NoRefCountPolicy        > SFUncountedPyFieldContainerPtrMFieldEditHandlePtr;


/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                      RecordedRefCountPolicy  > MFRecPyFieldContainerPtrMFieldEditHandlePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                      UnrecordedRefCountPolicy> MFUnrecPyFieldContainerPtrMFieldEditHandlePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                      WeakRefCountPolicy      > MFWeakPyFieldContainerPtrMFieldEditHandlePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                      NoRefCountPolicy        > MFUncountedPyFieldContainerPtrMFieldEditHandlePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFRecPyFieldContainerPtrMFieldEditHandlePtr : 
    public PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUnrecPyFieldContainerPtrMFieldEditHandlePtr : 
    public PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFWeakPyFieldContainerPtrMFieldEditHandlePtr :
    public PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUncountedPyFieldContainerPtrMFieldEditHandlePtr :
    public PointerSField<PyFieldContainerPtrMFieldEditHandle *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFRecPyFieldContainerPtrMFieldEditHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUnrecPyFieldContainerPtrMFieldEditHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFWeakPyFieldContainerPtrMFieldEditHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUncountedPyFieldContainerPtrMFieldEditHandlePtr :
    public PointerMField<PyFieldContainerPtrMFieldEditHandle *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPYFIELDCONTAINERPTRMFIELDEDITHANDLEFIELDS_H_ */
