/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPYTHONSCRIPTFIELDS_H_
#define _OSGPYTHONSCRIPTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGScriptingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class PythonScript;

OSG_GEN_CONTAINERPTR(PythonScript);
/*! \ingroup GrpScriptingFieldTraits
    \ingroup GrpLibOSGScripting
 */
template <>
struct FieldTraits<PythonScript *, nsOSG> :
    public FieldTraitsFCPtrBase<PythonScript *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<PythonScript *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SCRIPTING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPythonScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPythonScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPythonScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPythonScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPythonScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPythonScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPythonScriptPtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScript *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPythonScriptPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScript *,
                      RecordedRefCountPolicy, nsOSG  > SFRecPythonScriptPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScript *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecPythonScriptPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScript *,
                      WeakRefCountPolicy, nsOSG      > SFWeakPythonScriptPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScript *,
                      NoRefCountPolicy, nsOSG        > SFUncountedPythonScriptPtr;


/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScript *,
                      RecordedRefCountPolicy, nsOSG  > MFRecPythonScriptPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScript *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecPythonScriptPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScript *,
                      WeakRefCountPolicy, nsOSG      > MFWeakPythonScriptPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScript *,
                      NoRefCountPolicy, nsOSG        > MFUncountedPythonScriptPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFRecPythonScriptPtr : 
    public PointerSField<PythonScript *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUnrecPythonScriptPtr : 
    public PointerSField<PythonScript *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFWeakPythonScriptPtr :
    public PointerSField<PythonScript *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUncountedPythonScriptPtr :
    public PointerSField<PythonScript *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFRecPythonScriptPtr :
    public PointerMField<PythonScript *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUnrecPythonScriptPtr :
    public PointerMField<PythonScript *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFWeakPythonScriptPtr :
    public PointerMField<PythonScript *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUncountedPythonScriptPtr :
    public PointerMField<PythonScript *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPYTHONSCRIPTFIELDS_H_ */
