/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PythonScriptFile!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGAddOnsConfig.h"




#include "OSGPythonScriptFileBase.h"
#include "OSGPythonScriptFile.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::PythonScriptFile
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var std::string     PythonScriptFileBase::_sfScriptUrl
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<PythonScriptFile *, nsOSG>::_type(
    "PythonScriptFilePtr", 
    "PythonScriptPtr", 
    PythonScriptFile::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(PythonScriptFile *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           PythonScriptFile *,
                           nsOSG)

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           PythonScriptFile *,
                           nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void PythonScriptFileBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFString::Description(
        SFString::getClassType(),
        "scriptUrl",
        "",
        ScriptUrlFieldId, ScriptUrlFieldMask,
        false,
        (Field::FClusterLocal),
        static_cast<FieldEditMethodSig>(&PythonScriptFile::editHandleScriptUrl),
        static_cast<FieldGetMethodSig >(&PythonScriptFile::getHandleScriptUrl));

    oType.addInitialDesc(pDesc);
}


PythonScriptFileBase::TypeObject PythonScriptFileBase::_type(
    PythonScriptFileBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&PythonScriptFileBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&PythonScriptFile::initMethod),
    reinterpret_cast<ExitContainerF>(&PythonScriptFile::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(&PythonScriptFile::classDescInserter),
    true,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"PythonScriptFile\"\n"
    "    parent=\"PythonScript\"\n"
    "    library=\"Scripting\"\n"
    "    package=\"OSGAddOns\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    isNodeCore=\"true\"\n"
    "    docGroupBase=\"GrpScripting\"\n"
    "    typeDescAddable=\"true\"\n"
    "    dynFCDerived=\"true\"\n"
    "    >\n"
    "    <Field\n"
    "        name=\"scriptUrl\"\n"
    "        type=\"std::string\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        fieldFlags=\"FClusterLocal\"\n"
    "\t>\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &PythonScriptFileBase::getType(void)
{
    return _localType;
}

const FieldContainerType &PythonScriptFileBase::getType(void) const
{
    return _localType;
}

UInt32 PythonScriptFileBase::getContainerSize(void) const
{
    return sizeof(PythonScriptFile);
}

PythonScriptFileBase::TypeObject &PythonScriptFileBase::getFinalType(void)
{
    return _type;
}

const PythonScriptFileBase::TypeObject &PythonScriptFileBase::getFinalType(void) const
{
    return _type;
}

/*------------------------- decorator get ------------------------------*/


SFString *PythonScriptFileBase::editSFScriptUrl(void)
{
    editSField(ScriptUrlFieldMask);

    return &_sfScriptUrl;
}

const SFString *PythonScriptFileBase::getSFScriptUrl(void) const
{
    return &_sfScriptUrl;
}






/*------------------------------ access -----------------------------------*/

SizeT PythonScriptFileBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ScriptUrlFieldMask & whichField))
    {
        returnValue += _sfScriptUrl.getBinSize();
    }

    return returnValue;
}

void PythonScriptFileBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ScriptUrlFieldMask & whichField))
    {
        _sfScriptUrl.copyToBin(pMem);
    }
}

void PythonScriptFileBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ScriptUrlFieldMask & whichField))
    {
        editSField(ScriptUrlFieldMask);
        _sfScriptUrl.copyFromBin(pMem);
    }
}

//! create a new instance of the class
PythonScriptFileTransitPtr PythonScriptFileBase::createLocal(BitVector bFlags)
{
    PythonScriptFileTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<PythonScriptFile>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
PythonScriptFileTransitPtr PythonScriptFileBase::createDependent(BitVector bFlags)
{
    PythonScriptFileTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<PythonScriptFile>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
PythonScriptFileTransitPtr PythonScriptFileBase::create(void)
{
    PythonScriptFileTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<PythonScriptFile>(tmpPtr);
    }

    return fc;
}

PythonScriptFile *PythonScriptFileBase::createEmptyLocal(BitVector bFlags)
{
    PythonScriptFile *returnValue;

    newPtr<PythonScriptFile>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
PythonScriptFile *PythonScriptFileBase::createEmpty(void)
{
    PythonScriptFile *returnValue;

    newPtr<PythonScriptFile>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr PythonScriptFileBase::shallowCopyLocal(
    BitVector bFlags) const
{
    PythonScriptFile *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PythonScriptFile *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr PythonScriptFileBase::shallowCopyDependent(
    BitVector bFlags) const
{
    PythonScriptFile *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PythonScriptFile *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr PythonScriptFileBase::shallowCopy(void) const
{
    PythonScriptFile *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const PythonScriptFile *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

PythonScriptFileBase::PythonScriptFileBase(void) :
    Inherited(),
    _sfScriptUrl              ()
{
}

PythonScriptFileBase::PythonScriptFileBase(const PythonScriptFileBase &source) :
    Inherited(source),
    _sfScriptUrl              (source._sfScriptUrl              )
{
}


/*-------------------------- destructors ----------------------------------*/

PythonScriptFileBase::~PythonScriptFileBase(void)
{
}


GetFieldHandlePtr PythonScriptFileBase::getHandleScriptUrl       (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfScriptUrl,
             this->getType().getFieldDesc(ScriptUrlFieldId),
             const_cast<PythonScriptFileBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr PythonScriptFileBase::editHandleScriptUrl      (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfScriptUrl,
             this->getType().getFieldDesc(ScriptUrlFieldId),
             this));


    editSField(ScriptUrlFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void PythonScriptFileBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    PythonScriptFile *pThis = static_cast<PythonScriptFile *>(this);

    pThis->execSync(static_cast<PythonScriptFile *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *PythonScriptFileBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    PythonScriptFile *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const PythonScriptFile *>(pRefAspect),
                  dynamic_cast<const PythonScriptFile *>(this));

    return returnValue;
}
#endif

void PythonScriptFileBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
