/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PyFieldContainerPtrMFieldGetHandle!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGPyFieldContainerPtrMFieldGetHandleBase.h"
#include "OSGPyFieldContainerPtrMFieldGetHandle.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::PyFieldContainerPtrMFieldGetHandle
    A container used to expose a fieldcontainer pointer multi-field edit handle equivalent to Python. 
    It provides access to the underlying multi-field in a pythonic way.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<PyFieldContainerPtrMFieldGetHandle *, nsOSG>::_type(
    "PyFieldContainerPtrMFieldGetHandlePtr", 
    "FieldContainerPtr", 
    PyFieldContainerPtrMFieldGetHandle::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(PyFieldContainerPtrMFieldGetHandle *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           PyFieldContainerPtrMFieldGetHandle *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           PyFieldContainerPtrMFieldGetHandle *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void PyFieldContainerPtrMFieldGetHandleBase::classDescInserter(TypeObject &oType)
{
}


PyFieldContainerPtrMFieldGetHandleBase::TypeObject PyFieldContainerPtrMFieldGetHandleBase::_type(
    PyFieldContainerPtrMFieldGetHandleBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&PyFieldContainerPtrMFieldGetHandleBase::createEmptyLocal),
    PyFieldContainerPtrMFieldGetHandle::initMethod,
    PyFieldContainerPtrMFieldGetHandle::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&PyFieldContainerPtrMFieldGetHandle::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"PyFieldContainerPtrMFieldGetHandle\"\n"
    "   parent=\"FieldContainer\"\n"
    "   library=\"Scripting\"\n"
    "   structure=\"concrete\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   isNodeCore=\"false\"\n"
    "   docGroupBase=\"GrpScripting\"\n"
    "   >\n"
    "   A container used to expose a fieldcontainer pointer multi-field edit handle equivalent to Python. \n"
    "   It provides access to the underlying multi-field in a pythonic way.\n"
    "</FieldContainer>\n",
    "A container used to expose a fieldcontainer pointer multi-field edit handle equivalent to Python. \n"
    "It provides access to the underlying multi-field in a pythonic way.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &PyFieldContainerPtrMFieldGetHandleBase::getType(void)
{
    return _type;
}

const FieldContainerType &PyFieldContainerPtrMFieldGetHandleBase::getType(void) const
{
    return _type;
}

UInt32 PyFieldContainerPtrMFieldGetHandleBase::getContainerSize(void) const
{
    return sizeof(PyFieldContainerPtrMFieldGetHandle);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT PyFieldContainerPtrMFieldGetHandleBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void PyFieldContainerPtrMFieldGetHandleBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void PyFieldContainerPtrMFieldGetHandleBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
PyFieldContainerPtrMFieldGetHandleTransitPtr PyFieldContainerPtrMFieldGetHandleBase::createLocal(BitVector bFlags)
{
    PyFieldContainerPtrMFieldGetHandleTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<PyFieldContainerPtrMFieldGetHandle>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
PyFieldContainerPtrMFieldGetHandleTransitPtr PyFieldContainerPtrMFieldGetHandleBase::createDependent(BitVector bFlags)
{
    PyFieldContainerPtrMFieldGetHandleTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<PyFieldContainerPtrMFieldGetHandle>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
PyFieldContainerPtrMFieldGetHandleTransitPtr PyFieldContainerPtrMFieldGetHandleBase::create(void)
{
    PyFieldContainerPtrMFieldGetHandleTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<PyFieldContainerPtrMFieldGetHandle>(tmpPtr);
    }

    return fc;
}

PyFieldContainerPtrMFieldGetHandle *PyFieldContainerPtrMFieldGetHandleBase::createEmptyLocal(BitVector bFlags)
{
    PyFieldContainerPtrMFieldGetHandle *returnValue;

    newPtr<PyFieldContainerPtrMFieldGetHandle>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
PyFieldContainerPtrMFieldGetHandle *PyFieldContainerPtrMFieldGetHandleBase::createEmpty(void)
{
    PyFieldContainerPtrMFieldGetHandle *returnValue;

    newPtr<PyFieldContainerPtrMFieldGetHandle>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr PyFieldContainerPtrMFieldGetHandleBase::shallowCopyLocal(
    BitVector bFlags) const
{
    PyFieldContainerPtrMFieldGetHandle *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PyFieldContainerPtrMFieldGetHandle *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr PyFieldContainerPtrMFieldGetHandleBase::shallowCopyDependent(
    BitVector bFlags) const
{
    PyFieldContainerPtrMFieldGetHandle *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PyFieldContainerPtrMFieldGetHandle *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr PyFieldContainerPtrMFieldGetHandleBase::shallowCopy(void) const
{
    PyFieldContainerPtrMFieldGetHandle *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const PyFieldContainerPtrMFieldGetHandle *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

PyFieldContainerPtrMFieldGetHandleBase::PyFieldContainerPtrMFieldGetHandleBase(void) :
    Inherited()
{
}

PyFieldContainerPtrMFieldGetHandleBase::PyFieldContainerPtrMFieldGetHandleBase(const PyFieldContainerPtrMFieldGetHandleBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

PyFieldContainerPtrMFieldGetHandleBase::~PyFieldContainerPtrMFieldGetHandleBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void PyFieldContainerPtrMFieldGetHandleBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    PyFieldContainerPtrMFieldGetHandle *pThis = static_cast<PyFieldContainerPtrMFieldGetHandle *>(this);

    pThis->execSync(static_cast<PyFieldContainerPtrMFieldGetHandle *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *PyFieldContainerPtrMFieldGetHandleBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    PyFieldContainerPtrMFieldGetHandle *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const PyFieldContainerPtrMFieldGetHandle *>(pRefAspect),
                  dynamic_cast<const PyFieldContainerPtrMFieldGetHandle *>(this));

    return returnValue;
}
#endif

void PyFieldContainerPtrMFieldGetHandleBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
