/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPYTHONSCRIPTFILEFIELDS_H_
#define _OSGPYTHONSCRIPTFILEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribCSMDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PythonScriptFile;

OSG_GEN_CONTAINERPTR(PythonScriptFile);

/*! \ingroup GrpScriptingFieldTraits
    \ingroup GrpLibOSGContribCSM
 */
template <>
struct FieldTraits<PythonScriptFile *> :
    public FieldTraitsFCPtrBase<PythonScriptFile *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PythonScriptFile *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBCSM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPythonScriptFilePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPythonScriptFilePtr"; }
};

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPythonScriptFilePtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPythonScriptFilePtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPythonScriptFilePtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPythonScriptFilePtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPythonScriptFilePtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPythonScriptFilePtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPythonScriptFilePtr"; 
}

template<> inline
const Char8 *FieldTraits<PythonScriptFile *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPythonScriptFilePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScriptFile *,
                      RecordedRefCountPolicy  > SFRecPythonScriptFilePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScriptFile *,
                      UnrecordedRefCountPolicy> SFUnrecPythonScriptFilePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScriptFile *,
                      WeakRefCountPolicy      > SFWeakPythonScriptFilePtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PythonScriptFile *,
                      NoRefCountPolicy        > SFUncountedPythonScriptFilePtr;


/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScriptFile *,
                      RecordedRefCountPolicy  > MFRecPythonScriptFilePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScriptFile *,
                      UnrecordedRefCountPolicy> MFUnrecPythonScriptFilePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScriptFile *,
                      WeakRefCountPolicy      > MFWeakPythonScriptFilePtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PythonScriptFile *,
                      NoRefCountPolicy        > MFUncountedPythonScriptFilePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGContribCSM */
struct SFRecPythonScriptFilePtr : 
    public PointerSField<PythonScriptFile *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGContribCSM */
struct SFUnrecPythonScriptFilePtr : 
    public PointerSField<PythonScriptFile *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGContribCSM */
struct SFWeakPythonScriptFilePtr :
    public PointerSField<PythonScriptFile *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGContribCSM */
struct SFUncountedPythonScriptFilePtr :
    public PointerSField<PythonScriptFile *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGContribCSM */
struct MFRecPythonScriptFilePtr :
    public PointerMField<PythonScriptFile *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGContribCSM */
struct MFUnrecPythonScriptFilePtr :
    public PointerMField<PythonScriptFile *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGContribCSM */
struct MFWeakPythonScriptFilePtr :
    public PointerMField<PythonScriptFile *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGContribCSM */
struct MFUncountedPythonScriptFilePtr :
    public PointerMField<PythonScriptFile *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPYTHONSCRIPTFILEFIELDS_H_ */
