/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPYFIELDACCESSHANDLERFIELDS_H_
#define _OSGPYFIELDACCESSHANDLERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGScriptingDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class PyFieldAccessHandler;

OSG_GEN_CONTAINERPTR(PyFieldAccessHandler);
/*! \ingroup GrpScriptingFieldTraits
    \ingroup GrpLibOSGScripting
 */
template <>
struct FieldTraits<PyFieldAccessHandler *, nsOSG> :
    public FieldTraitsFCPtrBase<PyFieldAccessHandler *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<PyFieldAccessHandler *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SCRIPTING_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPyFieldAccessHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPyFieldAccessHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPyFieldAccessHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPyFieldAccessHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPyFieldAccessHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPyFieldAccessHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPyFieldAccessHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<PyFieldAccessHandler *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPyFieldAccessHandlerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldAccessHandler *,
                      RecordedRefCountPolicy, nsOSG  > SFRecPyFieldAccessHandlerPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldAccessHandler *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecPyFieldAccessHandlerPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldAccessHandler *,
                      WeakRefCountPolicy, nsOSG      > SFWeakPyFieldAccessHandlerPtr;
/*! \ingroup GrpScriptingFieldSFields */
typedef PointerSField<PyFieldAccessHandler *,
                      NoRefCountPolicy, nsOSG        > SFUncountedPyFieldAccessHandlerPtr;


/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldAccessHandler *,
                      RecordedRefCountPolicy, nsOSG  > MFRecPyFieldAccessHandlerPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldAccessHandler *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecPyFieldAccessHandlerPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldAccessHandler *,
                      WeakRefCountPolicy, nsOSG      > MFWeakPyFieldAccessHandlerPtr;
/*! \ingroup GrpScriptingFieldMFields */
typedef PointerMField<PyFieldAccessHandler *,
                      NoRefCountPolicy, nsOSG        > MFUncountedPyFieldAccessHandlerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFRecPyFieldAccessHandlerPtr : 
    public PointerSField<PyFieldAccessHandler *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUnrecPyFieldAccessHandlerPtr : 
    public PointerSField<PyFieldAccessHandler *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFWeakPyFieldAccessHandlerPtr :
    public PointerSField<PyFieldAccessHandler *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldSFields \ingroup GrpLibOSGScripting */
struct SFUncountedPyFieldAccessHandlerPtr :
    public PointerSField<PyFieldAccessHandler *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFRecPyFieldAccessHandlerPtr :
    public PointerMField<PyFieldAccessHandler *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUnrecPyFieldAccessHandlerPtr :
    public PointerMField<PyFieldAccessHandler *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFWeakPyFieldAccessHandlerPtr :
    public PointerMField<PyFieldAccessHandler *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpScriptingFieldMFields \ingroup GrpLibOSGScripting */
struct MFUncountedPyFieldAccessHandlerPtr :
    public PointerMField<PyFieldAccessHandler *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPYFIELDACCESSHANDLERFIELDS_H_ */
