/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BbqOutOfCoreDataSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGAddOnsConfig.h"




#include "OSGBbqOutOfCoreDataSourceBase.h"
#include "OSGBbqOutOfCoreDataSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BbqOutOfCoreDataSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var std::string     BbqOutOfCoreDataSourceBase::_sfFilename
    
*/

/*! \var Real32          BbqOutOfCoreDataSourceBase::_sfHeightScale
    
*/

/*! \var Real32          BbqOutOfCoreDataSourceBase::_sfHeightOffset
    
*/

/*! \var Real32          BbqOutOfCoreDataSourceBase::_sfSampleSpacing
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<BbqOutOfCoreDataSource *, nsOSG>::_type(
    "BbqOutOfCoreDataSourcePtr", 
    "BbqDataSourcePtr", 
    BbqOutOfCoreDataSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(BbqOutOfCoreDataSource *, nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BbqOutOfCoreDataSourceBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFString::Description(
        SFString::getClassType(),
        "filename",
        "",
        FilenameFieldId, FilenameFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BbqOutOfCoreDataSource::editHandleFilename),
        static_cast<FieldGetMethodSig >(&BbqOutOfCoreDataSource::getHandleFilename));

    oType.addInitialDesc(pDesc);

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "heightScale",
        "",
        HeightScaleFieldId, HeightScaleFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BbqOutOfCoreDataSource::editHandleHeightScale),
        static_cast<FieldGetMethodSig >(&BbqOutOfCoreDataSource::getHandleHeightScale));

    oType.addInitialDesc(pDesc);

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "heightOffset",
        "",
        HeightOffsetFieldId, HeightOffsetFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BbqOutOfCoreDataSource::editHandleHeightOffset),
        static_cast<FieldGetMethodSig >(&BbqOutOfCoreDataSource::getHandleHeightOffset));

    oType.addInitialDesc(pDesc);

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "sampleSpacing",
        "",
        SampleSpacingFieldId, SampleSpacingFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BbqOutOfCoreDataSource::editHandleSampleSpacing),
        static_cast<FieldGetMethodSig >(&BbqOutOfCoreDataSource::getHandleSampleSpacing));

    oType.addInitialDesc(pDesc);
}


BbqOutOfCoreDataSourceBase::TypeObject BbqOutOfCoreDataSourceBase::_type(
    BbqOutOfCoreDataSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&BbqOutOfCoreDataSourceBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&BbqOutOfCoreDataSource::initMethod),
    reinterpret_cast<ExitContainerF>(&BbqOutOfCoreDataSource::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(&BbqOutOfCoreDataSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BbqOutOfCoreDataSource\"\n"
    "    parent=\"BbqDataSource\"\n"
    "    pointerfieldtypes=\"none\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    library=\"ContribBbqTerrain\"\n"
    "    package=\"OSGAddOns\"\n"
    ">\n"
    "\t<Field\n"
    "\t\tname=\"filename\"\n"
    "\t\ttype=\"std::string\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\tdefaultValue=\"\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "\t</Field>\n"
    "\n"
    "\t<Field\n"
    "\t\tname=\"heightScale\"\n"
    "\t\ttype=\"Real32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\tdefaultValue=\"1.f\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "\t</Field>\n"
    "\n"
    "\t<Field\n"
    "\t\tname=\"heightOffset\"\n"
    "\t\ttype=\"Real32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\tdefaultValue=\"0.f\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "\t</Field>\n"
    "\n"
    "\t<Field\n"
    "\t\tname=\"sampleSpacing\"\n"
    "\t\ttype=\"Real32\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\tdefaultValue=\"1.f\"\n"
    "\t\taccess=\"public\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BbqOutOfCoreDataSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &BbqOutOfCoreDataSourceBase::getType(void) const
{
    return _type;
}

UInt32 BbqOutOfCoreDataSourceBase::getContainerSize(void) const
{
    return sizeof(BbqOutOfCoreDataSource);
}

/*------------------------- decorator get ------------------------------*/


SFString *BbqOutOfCoreDataSourceBase::editSFFilename(void)
{
    editSField(FilenameFieldMask);

    return &_sfFilename;
}

const SFString *BbqOutOfCoreDataSourceBase::getSFFilename(void) const
{
    return &_sfFilename;
}


SFReal32 *BbqOutOfCoreDataSourceBase::editSFHeightScale(void)
{
    editSField(HeightScaleFieldMask);

    return &_sfHeightScale;
}

const SFReal32 *BbqOutOfCoreDataSourceBase::getSFHeightScale(void) const
{
    return &_sfHeightScale;
}


SFReal32 *BbqOutOfCoreDataSourceBase::editSFHeightOffset(void)
{
    editSField(HeightOffsetFieldMask);

    return &_sfHeightOffset;
}

const SFReal32 *BbqOutOfCoreDataSourceBase::getSFHeightOffset(void) const
{
    return &_sfHeightOffset;
}


SFReal32 *BbqOutOfCoreDataSourceBase::editSFSampleSpacing(void)
{
    editSField(SampleSpacingFieldMask);

    return &_sfSampleSpacing;
}

const SFReal32 *BbqOutOfCoreDataSourceBase::getSFSampleSpacing(void) const
{
    return &_sfSampleSpacing;
}






/*------------------------------ access -----------------------------------*/

SizeT BbqOutOfCoreDataSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (FilenameFieldMask & whichField))
    {
        returnValue += _sfFilename.getBinSize();
    }
    if(FieldBits::NoField != (HeightScaleFieldMask & whichField))
    {
        returnValue += _sfHeightScale.getBinSize();
    }
    if(FieldBits::NoField != (HeightOffsetFieldMask & whichField))
    {
        returnValue += _sfHeightOffset.getBinSize();
    }
    if(FieldBits::NoField != (SampleSpacingFieldMask & whichField))
    {
        returnValue += _sfSampleSpacing.getBinSize();
    }

    return returnValue;
}

void BbqOutOfCoreDataSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (FilenameFieldMask & whichField))
    {
        _sfFilename.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightScaleFieldMask & whichField))
    {
        _sfHeightScale.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightOffsetFieldMask & whichField))
    {
        _sfHeightOffset.copyToBin(pMem);
    }
    if(FieldBits::NoField != (SampleSpacingFieldMask & whichField))
    {
        _sfSampleSpacing.copyToBin(pMem);
    }
}

void BbqOutOfCoreDataSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (FilenameFieldMask & whichField))
    {
        editSField(FilenameFieldMask);
        _sfFilename.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightScaleFieldMask & whichField))
    {
        editSField(HeightScaleFieldMask);
        _sfHeightScale.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightOffsetFieldMask & whichField))
    {
        editSField(HeightOffsetFieldMask);
        _sfHeightOffset.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (SampleSpacingFieldMask & whichField))
    {
        editSField(SampleSpacingFieldMask);
        _sfSampleSpacing.copyFromBin(pMem);
    }
}

//! create a new instance of the class
BbqOutOfCoreDataSourceTransitPtr BbqOutOfCoreDataSourceBase::createLocal(BitVector bFlags)
{
    BbqOutOfCoreDataSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BbqOutOfCoreDataSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BbqOutOfCoreDataSourceTransitPtr BbqOutOfCoreDataSourceBase::createDependent(BitVector bFlags)
{
    BbqOutOfCoreDataSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BbqOutOfCoreDataSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BbqOutOfCoreDataSourceTransitPtr BbqOutOfCoreDataSourceBase::create(void)
{
    BbqOutOfCoreDataSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BbqOutOfCoreDataSource>(tmpPtr);
    }

    return fc;
}

BbqOutOfCoreDataSource *BbqOutOfCoreDataSourceBase::createEmptyLocal(BitVector bFlags)
{
    BbqOutOfCoreDataSource *returnValue;

    newPtr<BbqOutOfCoreDataSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BbqOutOfCoreDataSource *BbqOutOfCoreDataSourceBase::createEmpty(void)
{
    BbqOutOfCoreDataSource *returnValue;

    newPtr<BbqOutOfCoreDataSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr BbqOutOfCoreDataSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BbqOutOfCoreDataSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BbqOutOfCoreDataSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BbqOutOfCoreDataSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BbqOutOfCoreDataSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BbqOutOfCoreDataSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BbqOutOfCoreDataSourceBase::shallowCopy(void) const
{
    BbqOutOfCoreDataSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BbqOutOfCoreDataSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

BbqOutOfCoreDataSourceBase::BbqOutOfCoreDataSourceBase(void) :
    Inherited(),
    _sfFilename               (),
    _sfHeightScale            (Real32(1.f)),
    _sfHeightOffset           (Real32(0.f)),
    _sfSampleSpacing          (Real32(1.f))
{
}

BbqOutOfCoreDataSourceBase::BbqOutOfCoreDataSourceBase(const BbqOutOfCoreDataSourceBase &source) :
    Inherited(source),
    _sfFilename               (source._sfFilename               ),
    _sfHeightScale            (source._sfHeightScale            ),
    _sfHeightOffset           (source._sfHeightOffset           ),
    _sfSampleSpacing          (source._sfSampleSpacing          )
{
}


/*-------------------------- destructors ----------------------------------*/

BbqOutOfCoreDataSourceBase::~BbqOutOfCoreDataSourceBase(void)
{
}


GetFieldHandlePtr BbqOutOfCoreDataSourceBase::getHandleFilename        (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfFilename,
             this->getType().getFieldDesc(FilenameFieldId),
             const_cast<BbqOutOfCoreDataSourceBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BbqOutOfCoreDataSourceBase::editHandleFilename       (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfFilename,
             this->getType().getFieldDesc(FilenameFieldId),
             this));


    editSField(FilenameFieldMask);

    return returnValue;
}

GetFieldHandlePtr BbqOutOfCoreDataSourceBase::getHandleHeightScale     (void) const
{
    SFReal32::GetHandlePtr returnValue(
        new  SFReal32::GetHandle(
             &_sfHeightScale,
             this->getType().getFieldDesc(HeightScaleFieldId),
             const_cast<BbqOutOfCoreDataSourceBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BbqOutOfCoreDataSourceBase::editHandleHeightScale    (void)
{
    SFReal32::EditHandlePtr returnValue(
        new  SFReal32::EditHandle(
             &_sfHeightScale,
             this->getType().getFieldDesc(HeightScaleFieldId),
             this));


    editSField(HeightScaleFieldMask);

    return returnValue;
}

GetFieldHandlePtr BbqOutOfCoreDataSourceBase::getHandleHeightOffset    (void) const
{
    SFReal32::GetHandlePtr returnValue(
        new  SFReal32::GetHandle(
             &_sfHeightOffset,
             this->getType().getFieldDesc(HeightOffsetFieldId),
             const_cast<BbqOutOfCoreDataSourceBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BbqOutOfCoreDataSourceBase::editHandleHeightOffset   (void)
{
    SFReal32::EditHandlePtr returnValue(
        new  SFReal32::EditHandle(
             &_sfHeightOffset,
             this->getType().getFieldDesc(HeightOffsetFieldId),
             this));


    editSField(HeightOffsetFieldMask);

    return returnValue;
}

GetFieldHandlePtr BbqOutOfCoreDataSourceBase::getHandleSampleSpacing   (void) const
{
    SFReal32::GetHandlePtr returnValue(
        new  SFReal32::GetHandle(
             &_sfSampleSpacing,
             this->getType().getFieldDesc(SampleSpacingFieldId),
             const_cast<BbqOutOfCoreDataSourceBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BbqOutOfCoreDataSourceBase::editHandleSampleSpacing  (void)
{
    SFReal32::EditHandlePtr returnValue(
        new  SFReal32::EditHandle(
             &_sfSampleSpacing,
             this->getType().getFieldDesc(SampleSpacingFieldId),
             this));


    editSField(SampleSpacingFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void BbqOutOfCoreDataSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BbqOutOfCoreDataSource *pThis = static_cast<BbqOutOfCoreDataSource *>(this);

    pThis->execSync(static_cast<BbqOutOfCoreDataSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BbqOutOfCoreDataSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BbqOutOfCoreDataSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BbqOutOfCoreDataSource *>(pRefAspect),
                  dynamic_cast<const BbqOutOfCoreDataSource *>(this));

    return returnValue;
}
#endif

void BbqOutOfCoreDataSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
