/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DynamicTerrain!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGAddOnsConfig.h"



#include "OSGImage.h"                   // HeightData Class
#include "OSGTextureObjChunk.h"         // HeightColorTexture Class

#include "OSGDynamicTerrainBase.h"
#include "OSGDynamicTerrain.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::DynamicTerrain
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Int32           DynamicTerrainBase::_sfLevelSize
    
*/

/*! \var Image *         DynamicTerrainBase::_sfHeightData
    
*/

/*! \var Real32          DynamicTerrainBase::_sfHeightDataScale
    
*/

/*! \var Real32          DynamicTerrainBase::_sfHeightDataOffset
    
*/

/*! \var Real32          DynamicTerrainBase::_sfSampleDistance
    
*/

/*! \var Image *         DynamicTerrainBase::_sfTextureData
    
*/

/*! \var TextureObjChunk * DynamicTerrainBase::_sfHeightColorTexture
    
*/

/*! \var Int32           DynamicTerrainBase::_sfSampleUpdateBudget
    
*/

/*! \var bool            DynamicTerrainBase::_sfEnableFrustumCulling
    
*/

/*! \var bool            DynamicTerrainBase::_sfUseGpuRenderer
    
*/

/*! \var bool            DynamicTerrainBase::_sfUseVboExtension
    
*/

/*! \var bool            DynamicTerrainBase::_sfEnableSmoothTransition
    
*/

/*! \var bool            DynamicTerrainBase::_sfShowBoundingBoxes
    
*/

/*! \var bool            DynamicTerrainBase::_sfShowTransitionRegions
    
*/

/*! \var bool            DynamicTerrainBase::_sfDisableUpdate
    
*/

/*! \var std::string     DynamicTerrainBase::_sfCpuVertexProgram
    
*/

/*! \var std::string     DynamicTerrainBase::_sfCpuFragmentProgram
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<DynamicTerrain *, nsOSG>::_type(
    "DynamicTerrainPtr", 
    "MaterialDrawablePtr", 
    DynamicTerrain::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(DynamicTerrain *, nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void DynamicTerrainBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFInt32::Description(
        SFInt32::getClassType(),
        "levelSize",
        "",
        LevelSizeFieldId, LevelSizeFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleLevelSize),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleLevelSize));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecImagePtr::Description(
        SFUnrecImagePtr::getClassType(),
        "heightData",
        "",
        HeightDataFieldId, HeightDataFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleHeightData),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleHeightData));

    oType.addInitialDesc(pDesc);

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "heightDataScale",
        "",
        HeightDataScaleFieldId, HeightDataScaleFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleHeightDataScale),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleHeightDataScale));

    oType.addInitialDesc(pDesc);

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "heightDataOffset",
        "",
        HeightDataOffsetFieldId, HeightDataOffsetFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleHeightDataOffset),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleHeightDataOffset));

    oType.addInitialDesc(pDesc);

    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "sampleDistance",
        "",
        SampleDistanceFieldId, SampleDistanceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleSampleDistance),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleSampleDistance));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecImagePtr::Description(
        SFUnrecImagePtr::getClassType(),
        "textureData",
        "",
        TextureDataFieldId, TextureDataFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleTextureData),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleTextureData));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecTextureObjChunkPtr::Description(
        SFUnrecTextureObjChunkPtr::getClassType(),
        "heightColorTexture",
        "",
        HeightColorTextureFieldId, HeightColorTextureFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleHeightColorTexture),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleHeightColorTexture));

    oType.addInitialDesc(pDesc);

    pDesc = new SFInt32::Description(
        SFInt32::getClassType(),
        "sampleUpdateBudget",
        "",
        SampleUpdateBudgetFieldId, SampleUpdateBudgetFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleSampleUpdateBudget),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleSampleUpdateBudget));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "enableFrustumCulling",
        "",
        EnableFrustumCullingFieldId, EnableFrustumCullingFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleEnableFrustumCulling),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleEnableFrustumCulling));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "useGpuRenderer",
        "",
        UseGpuRendererFieldId, UseGpuRendererFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleUseGpuRenderer),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleUseGpuRenderer));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "useVboExtension",
        "",
        UseVboExtensionFieldId, UseVboExtensionFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleUseVboExtension),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleUseVboExtension));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "enableSmoothTransition",
        "",
        EnableSmoothTransitionFieldId, EnableSmoothTransitionFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleEnableSmoothTransition),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleEnableSmoothTransition));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "showBoundingBoxes",
        "",
        ShowBoundingBoxesFieldId, ShowBoundingBoxesFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleShowBoundingBoxes),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleShowBoundingBoxes));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "showTransitionRegions",
        "",
        ShowTransitionRegionsFieldId, ShowTransitionRegionsFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleShowTransitionRegions),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleShowTransitionRegions));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "disableUpdate",
        "",
        DisableUpdateFieldId, DisableUpdateFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleDisableUpdate),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleDisableUpdate));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "cpuVertexProgram",
        "",
        CpuVertexProgramFieldId, CpuVertexProgramFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleCpuVertexProgram),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleCpuVertexProgram));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "cpuFragmentProgram",
        "",
        CpuFragmentProgramFieldId, CpuFragmentProgramFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DynamicTerrain::editHandleCpuFragmentProgram),
        static_cast<FieldGetMethodSig >(&DynamicTerrain::getHandleCpuFragmentProgram));

    oType.addInitialDesc(pDesc);
}


DynamicTerrainBase::TypeObject DynamicTerrainBase::_type(
    DynamicTerrainBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&DynamicTerrainBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&DynamicTerrain::initMethod),
    reinterpret_cast<ExitContainerF>(&DynamicTerrain::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(&DynamicTerrain::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"DynamicTerrain\"\n"
    "    parent=\"MaterialDrawable\"\n"
    "    pointerfieldtypes=\"none\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    library=\"ContribDynamicTerrain\"\n"
    "    package=\"OSGAddOns\"\n"
    "    >\n"
    "  <Field\n"
    "      name=\"levelSize\"\n"
    "      type=\"Int32\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"63\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"heightData\"\n"
    "      type=\"ImagePtr\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"heightDataScale\"\n"
    "      type=\"Real32\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"1.0\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"heightDataOffset\"\n"
    "      type=\"Real32\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"0\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"sampleDistance\"\n"
    "      type=\"Real32\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"1.0\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"textureData\"\n"
    "      type=\"ImagePtr\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>  \n"
    "  <Field\n"
    "      name=\"heightColorTexture\"\n"
    "      type=\"TextureObjChunkPtr\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"sampleUpdateBudget\"\n"
    "      type=\"Int32\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"enableFrustumCulling\"\n"
    "      type=\"bool\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"useGpuRenderer\"\n"
    "      type=\"bool\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"false\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"useVboExtension\"\n"
    "      type=\"bool\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"true\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"enableSmoothTransition\"\n"
    "      type=\"bool\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"showBoundingBoxes\"\n"
    "      type=\"bool\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"showTransitionRegions\"\n"
    "      type=\"bool\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"false\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"disableUpdate\"\n"
    "      type=\"bool\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"false\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"cpuVertexProgram\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"cpuFragmentProgram\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      defaultValue=\"\"\n"
    "      >\n"
    "  </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &DynamicTerrainBase::getType(void)
{
    return _type;
}

const FieldContainerType &DynamicTerrainBase::getType(void) const
{
    return _type;
}

UInt32 DynamicTerrainBase::getContainerSize(void) const
{
    return sizeof(DynamicTerrain);
}

/*------------------------- decorator get ------------------------------*/


SFInt32 *DynamicTerrainBase::editSFLevelSize(void)
{
    editSField(LevelSizeFieldMask);

    return &_sfLevelSize;
}

const SFInt32 *DynamicTerrainBase::getSFLevelSize(void) const
{
    return &_sfLevelSize;
}


//! Get the DynamicTerrain::_sfHeightData field.
const SFUnrecImagePtr *DynamicTerrainBase::getSFHeightData(void) const
{
    return &_sfHeightData;
}

SFUnrecImagePtr     *DynamicTerrainBase::editSFHeightData     (void)
{
    editSField(HeightDataFieldMask);

    return &_sfHeightData;
}

//! Get the value of the DynamicTerrain::_sfHeightData field.
Image * DynamicTerrainBase::getHeightData(void) const
{
    return _sfHeightData.getValue();
}

//! Set the value of the DynamicTerrain::_sfHeightData field.
void DynamicTerrainBase::setHeightData(Image * const value)
{
    editSField(HeightDataFieldMask);

    _sfHeightData.setValue(value);
}


SFReal32 *DynamicTerrainBase::editSFHeightDataScale(void)
{
    editSField(HeightDataScaleFieldMask);

    return &_sfHeightDataScale;
}

const SFReal32 *DynamicTerrainBase::getSFHeightDataScale(void) const
{
    return &_sfHeightDataScale;
}


SFReal32 *DynamicTerrainBase::editSFHeightDataOffset(void)
{
    editSField(HeightDataOffsetFieldMask);

    return &_sfHeightDataOffset;
}

const SFReal32 *DynamicTerrainBase::getSFHeightDataOffset(void) const
{
    return &_sfHeightDataOffset;
}


SFReal32 *DynamicTerrainBase::editSFSampleDistance(void)
{
    editSField(SampleDistanceFieldMask);

    return &_sfSampleDistance;
}

const SFReal32 *DynamicTerrainBase::getSFSampleDistance(void) const
{
    return &_sfSampleDistance;
}


//! Get the DynamicTerrain::_sfTextureData field.
const SFUnrecImagePtr *DynamicTerrainBase::getSFTextureData(void) const
{
    return &_sfTextureData;
}

SFUnrecImagePtr     *DynamicTerrainBase::editSFTextureData    (void)
{
    editSField(TextureDataFieldMask);

    return &_sfTextureData;
}

//! Get the value of the DynamicTerrain::_sfTextureData field.
Image * DynamicTerrainBase::getTextureData(void) const
{
    return _sfTextureData.getValue();
}

//! Set the value of the DynamicTerrain::_sfTextureData field.
void DynamicTerrainBase::setTextureData(Image * const value)
{
    editSField(TextureDataFieldMask);

    _sfTextureData.setValue(value);
}


//! Get the DynamicTerrain::_sfHeightColorTexture field.
const SFUnrecTextureObjChunkPtr *DynamicTerrainBase::getSFHeightColorTexture(void) const
{
    return &_sfHeightColorTexture;
}

SFUnrecTextureObjChunkPtr *DynamicTerrainBase::editSFHeightColorTexture(void)
{
    editSField(HeightColorTextureFieldMask);

    return &_sfHeightColorTexture;
}

//! Get the value of the DynamicTerrain::_sfHeightColorTexture field.
TextureObjChunk * DynamicTerrainBase::getHeightColorTexture(void) const
{
    return _sfHeightColorTexture.getValue();
}

//! Set the value of the DynamicTerrain::_sfHeightColorTexture field.
void DynamicTerrainBase::setHeightColorTexture(TextureObjChunk * const value)
{
    editSField(HeightColorTextureFieldMask);

    _sfHeightColorTexture.setValue(value);
}


SFInt32 *DynamicTerrainBase::editSFSampleUpdateBudget(void)
{
    editSField(SampleUpdateBudgetFieldMask);

    return &_sfSampleUpdateBudget;
}

const SFInt32 *DynamicTerrainBase::getSFSampleUpdateBudget(void) const
{
    return &_sfSampleUpdateBudget;
}


SFBool *DynamicTerrainBase::editSFEnableFrustumCulling(void)
{
    editSField(EnableFrustumCullingFieldMask);

    return &_sfEnableFrustumCulling;
}

const SFBool *DynamicTerrainBase::getSFEnableFrustumCulling(void) const
{
    return &_sfEnableFrustumCulling;
}


SFBool *DynamicTerrainBase::editSFUseGpuRenderer(void)
{
    editSField(UseGpuRendererFieldMask);

    return &_sfUseGpuRenderer;
}

const SFBool *DynamicTerrainBase::getSFUseGpuRenderer(void) const
{
    return &_sfUseGpuRenderer;
}


SFBool *DynamicTerrainBase::editSFUseVboExtension(void)
{
    editSField(UseVboExtensionFieldMask);

    return &_sfUseVboExtension;
}

const SFBool *DynamicTerrainBase::getSFUseVboExtension(void) const
{
    return &_sfUseVboExtension;
}


SFBool *DynamicTerrainBase::editSFEnableSmoothTransition(void)
{
    editSField(EnableSmoothTransitionFieldMask);

    return &_sfEnableSmoothTransition;
}

const SFBool *DynamicTerrainBase::getSFEnableSmoothTransition(void) const
{
    return &_sfEnableSmoothTransition;
}


SFBool *DynamicTerrainBase::editSFShowBoundingBoxes(void)
{
    editSField(ShowBoundingBoxesFieldMask);

    return &_sfShowBoundingBoxes;
}

const SFBool *DynamicTerrainBase::getSFShowBoundingBoxes(void) const
{
    return &_sfShowBoundingBoxes;
}


SFBool *DynamicTerrainBase::editSFShowTransitionRegions(void)
{
    editSField(ShowTransitionRegionsFieldMask);

    return &_sfShowTransitionRegions;
}

const SFBool *DynamicTerrainBase::getSFShowTransitionRegions(void) const
{
    return &_sfShowTransitionRegions;
}


SFBool *DynamicTerrainBase::editSFDisableUpdate(void)
{
    editSField(DisableUpdateFieldMask);

    return &_sfDisableUpdate;
}

const SFBool *DynamicTerrainBase::getSFDisableUpdate(void) const
{
    return &_sfDisableUpdate;
}


SFString *DynamicTerrainBase::editSFCpuVertexProgram(void)
{
    editSField(CpuVertexProgramFieldMask);

    return &_sfCpuVertexProgram;
}

const SFString *DynamicTerrainBase::getSFCpuVertexProgram(void) const
{
    return &_sfCpuVertexProgram;
}


SFString *DynamicTerrainBase::editSFCpuFragmentProgram(void)
{
    editSField(CpuFragmentProgramFieldMask);

    return &_sfCpuFragmentProgram;
}

const SFString *DynamicTerrainBase::getSFCpuFragmentProgram(void) const
{
    return &_sfCpuFragmentProgram;
}






/*------------------------------ access -----------------------------------*/

SizeT DynamicTerrainBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (LevelSizeFieldMask & whichField))
    {
        returnValue += _sfLevelSize.getBinSize();
    }
    if(FieldBits::NoField != (HeightDataFieldMask & whichField))
    {
        returnValue += _sfHeightData.getBinSize();
    }
    if(FieldBits::NoField != (HeightDataScaleFieldMask & whichField))
    {
        returnValue += _sfHeightDataScale.getBinSize();
    }
    if(FieldBits::NoField != (HeightDataOffsetFieldMask & whichField))
    {
        returnValue += _sfHeightDataOffset.getBinSize();
    }
    if(FieldBits::NoField != (SampleDistanceFieldMask & whichField))
    {
        returnValue += _sfSampleDistance.getBinSize();
    }
    if(FieldBits::NoField != (TextureDataFieldMask & whichField))
    {
        returnValue += _sfTextureData.getBinSize();
    }
    if(FieldBits::NoField != (HeightColorTextureFieldMask & whichField))
    {
        returnValue += _sfHeightColorTexture.getBinSize();
    }
    if(FieldBits::NoField != (SampleUpdateBudgetFieldMask & whichField))
    {
        returnValue += _sfSampleUpdateBudget.getBinSize();
    }
    if(FieldBits::NoField != (EnableFrustumCullingFieldMask & whichField))
    {
        returnValue += _sfEnableFrustumCulling.getBinSize();
    }
    if(FieldBits::NoField != (UseGpuRendererFieldMask & whichField))
    {
        returnValue += _sfUseGpuRenderer.getBinSize();
    }
    if(FieldBits::NoField != (UseVboExtensionFieldMask & whichField))
    {
        returnValue += _sfUseVboExtension.getBinSize();
    }
    if(FieldBits::NoField != (EnableSmoothTransitionFieldMask & whichField))
    {
        returnValue += _sfEnableSmoothTransition.getBinSize();
    }
    if(FieldBits::NoField != (ShowBoundingBoxesFieldMask & whichField))
    {
        returnValue += _sfShowBoundingBoxes.getBinSize();
    }
    if(FieldBits::NoField != (ShowTransitionRegionsFieldMask & whichField))
    {
        returnValue += _sfShowTransitionRegions.getBinSize();
    }
    if(FieldBits::NoField != (DisableUpdateFieldMask & whichField))
    {
        returnValue += _sfDisableUpdate.getBinSize();
    }
    if(FieldBits::NoField != (CpuVertexProgramFieldMask & whichField))
    {
        returnValue += _sfCpuVertexProgram.getBinSize();
    }
    if(FieldBits::NoField != (CpuFragmentProgramFieldMask & whichField))
    {
        returnValue += _sfCpuFragmentProgram.getBinSize();
    }

    return returnValue;
}

void DynamicTerrainBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (LevelSizeFieldMask & whichField))
    {
        _sfLevelSize.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataFieldMask & whichField))
    {
        _sfHeightData.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataScaleFieldMask & whichField))
    {
        _sfHeightDataScale.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataOffsetFieldMask & whichField))
    {
        _sfHeightDataOffset.copyToBin(pMem);
    }
    if(FieldBits::NoField != (SampleDistanceFieldMask & whichField))
    {
        _sfSampleDistance.copyToBin(pMem);
    }
    if(FieldBits::NoField != (TextureDataFieldMask & whichField))
    {
        _sfTextureData.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightColorTextureFieldMask & whichField))
    {
        _sfHeightColorTexture.copyToBin(pMem);
    }
    if(FieldBits::NoField != (SampleUpdateBudgetFieldMask & whichField))
    {
        _sfSampleUpdateBudget.copyToBin(pMem);
    }
    if(FieldBits::NoField != (EnableFrustumCullingFieldMask & whichField))
    {
        _sfEnableFrustumCulling.copyToBin(pMem);
    }
    if(FieldBits::NoField != (UseGpuRendererFieldMask & whichField))
    {
        _sfUseGpuRenderer.copyToBin(pMem);
    }
    if(FieldBits::NoField != (UseVboExtensionFieldMask & whichField))
    {
        _sfUseVboExtension.copyToBin(pMem);
    }
    if(FieldBits::NoField != (EnableSmoothTransitionFieldMask & whichField))
    {
        _sfEnableSmoothTransition.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ShowBoundingBoxesFieldMask & whichField))
    {
        _sfShowBoundingBoxes.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ShowTransitionRegionsFieldMask & whichField))
    {
        _sfShowTransitionRegions.copyToBin(pMem);
    }
    if(FieldBits::NoField != (DisableUpdateFieldMask & whichField))
    {
        _sfDisableUpdate.copyToBin(pMem);
    }
    if(FieldBits::NoField != (CpuVertexProgramFieldMask & whichField))
    {
        _sfCpuVertexProgram.copyToBin(pMem);
    }
    if(FieldBits::NoField != (CpuFragmentProgramFieldMask & whichField))
    {
        _sfCpuFragmentProgram.copyToBin(pMem);
    }
}

void DynamicTerrainBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (LevelSizeFieldMask & whichField))
    {
        editSField(LevelSizeFieldMask);
        _sfLevelSize.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataFieldMask & whichField))
    {
        editSField(HeightDataFieldMask);
        _sfHeightData.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataScaleFieldMask & whichField))
    {
        editSField(HeightDataScaleFieldMask);
        _sfHeightDataScale.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightDataOffsetFieldMask & whichField))
    {
        editSField(HeightDataOffsetFieldMask);
        _sfHeightDataOffset.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (SampleDistanceFieldMask & whichField))
    {
        editSField(SampleDistanceFieldMask);
        _sfSampleDistance.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (TextureDataFieldMask & whichField))
    {
        editSField(TextureDataFieldMask);
        _sfTextureData.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightColorTextureFieldMask & whichField))
    {
        editSField(HeightColorTextureFieldMask);
        _sfHeightColorTexture.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (SampleUpdateBudgetFieldMask & whichField))
    {
        editSField(SampleUpdateBudgetFieldMask);
        _sfSampleUpdateBudget.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (EnableFrustumCullingFieldMask & whichField))
    {
        editSField(EnableFrustumCullingFieldMask);
        _sfEnableFrustumCulling.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (UseGpuRendererFieldMask & whichField))
    {
        editSField(UseGpuRendererFieldMask);
        _sfUseGpuRenderer.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (UseVboExtensionFieldMask & whichField))
    {
        editSField(UseVboExtensionFieldMask);
        _sfUseVboExtension.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (EnableSmoothTransitionFieldMask & whichField))
    {
        editSField(EnableSmoothTransitionFieldMask);
        _sfEnableSmoothTransition.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ShowBoundingBoxesFieldMask & whichField))
    {
        editSField(ShowBoundingBoxesFieldMask);
        _sfShowBoundingBoxes.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ShowTransitionRegionsFieldMask & whichField))
    {
        editSField(ShowTransitionRegionsFieldMask);
        _sfShowTransitionRegions.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (DisableUpdateFieldMask & whichField))
    {
        editSField(DisableUpdateFieldMask);
        _sfDisableUpdate.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (CpuVertexProgramFieldMask & whichField))
    {
        editSField(CpuVertexProgramFieldMask);
        _sfCpuVertexProgram.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (CpuFragmentProgramFieldMask & whichField))
    {
        editSField(CpuFragmentProgramFieldMask);
        _sfCpuFragmentProgram.copyFromBin(pMem);
    }
}

//! create a new instance of the class
DynamicTerrainTransitPtr DynamicTerrainBase::createLocal(BitVector bFlags)
{
    DynamicTerrainTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<DynamicTerrain>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
DynamicTerrainTransitPtr DynamicTerrainBase::createDependent(BitVector bFlags)
{
    DynamicTerrainTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<DynamicTerrain>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
DynamicTerrainTransitPtr DynamicTerrainBase::create(void)
{
    DynamicTerrainTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<DynamicTerrain>(tmpPtr);
    }

    return fc;
}

DynamicTerrain *DynamicTerrainBase::createEmptyLocal(BitVector bFlags)
{
    DynamicTerrain *returnValue;

    newPtr<DynamicTerrain>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
DynamicTerrain *DynamicTerrainBase::createEmpty(void)
{
    DynamicTerrain *returnValue;

    newPtr<DynamicTerrain>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr DynamicTerrainBase::shallowCopyLocal(
    BitVector bFlags) const
{
    DynamicTerrain *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const DynamicTerrain *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr DynamicTerrainBase::shallowCopyDependent(
    BitVector bFlags) const
{
    DynamicTerrain *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const DynamicTerrain *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr DynamicTerrainBase::shallowCopy(void) const
{
    DynamicTerrain *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const DynamicTerrain *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

DynamicTerrainBase::DynamicTerrainBase(void) :
    Inherited(),
    _sfLevelSize              (Int32(63)),
    _sfHeightData             (NULL),
    _sfHeightDataScale        (Real32(1.0)),
    _sfHeightDataOffset       (Real32(0)),
    _sfSampleDistance         (Real32(1.0)),
    _sfTextureData            (NULL),
    _sfHeightColorTexture     (NULL),
    _sfSampleUpdateBudget     (),
    _sfEnableFrustumCulling   (),
    _sfUseGpuRenderer         (bool(false)),
    _sfUseVboExtension        (bool(true)),
    _sfEnableSmoothTransition (),
    _sfShowBoundingBoxes      (),
    _sfShowTransitionRegions  (bool(false)),
    _sfDisableUpdate          (bool(false)),
    _sfCpuVertexProgram       (),
    _sfCpuFragmentProgram     ()
{
}

DynamicTerrainBase::DynamicTerrainBase(const DynamicTerrainBase &source) :
    Inherited(source),
    _sfLevelSize              (source._sfLevelSize              ),
    _sfHeightData             (NULL),
    _sfHeightDataScale        (source._sfHeightDataScale        ),
    _sfHeightDataOffset       (source._sfHeightDataOffset       ),
    _sfSampleDistance         (source._sfSampleDistance         ),
    _sfTextureData            (NULL),
    _sfHeightColorTexture     (NULL),
    _sfSampleUpdateBudget     (source._sfSampleUpdateBudget     ),
    _sfEnableFrustumCulling   (source._sfEnableFrustumCulling   ),
    _sfUseGpuRenderer         (source._sfUseGpuRenderer         ),
    _sfUseVboExtension        (source._sfUseVboExtension        ),
    _sfEnableSmoothTransition (source._sfEnableSmoothTransition ),
    _sfShowBoundingBoxes      (source._sfShowBoundingBoxes      ),
    _sfShowTransitionRegions  (source._sfShowTransitionRegions  ),
    _sfDisableUpdate          (source._sfDisableUpdate          ),
    _sfCpuVertexProgram       (source._sfCpuVertexProgram       ),
    _sfCpuFragmentProgram     (source._sfCpuFragmentProgram     )
{
}


/*-------------------------- destructors ----------------------------------*/

DynamicTerrainBase::~DynamicTerrainBase(void)
{
}

void DynamicTerrainBase::onCreate(const DynamicTerrain *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        DynamicTerrain *pThis = static_cast<DynamicTerrain *>(this);

        pThis->setHeightData(source->getHeightData());

        pThis->setTextureData(source->getTextureData());

        pThis->setHeightColorTexture(source->getHeightColorTexture());
    }
}

GetFieldHandlePtr DynamicTerrainBase::getHandleLevelSize       (void) const
{
    SFInt32::GetHandlePtr returnValue(
        new  SFInt32::GetHandle(
             &_sfLevelSize,
             this->getType().getFieldDesc(LevelSizeFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleLevelSize      (void)
{
    SFInt32::EditHandlePtr returnValue(
        new  SFInt32::EditHandle(
             &_sfLevelSize,
             this->getType().getFieldDesc(LevelSizeFieldId),
             this));


    editSField(LevelSizeFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleHeightData      (void) const
{
    SFUnrecImagePtr::GetHandlePtr returnValue(
        new  SFUnrecImagePtr::GetHandle(
             &_sfHeightData,
             this->getType().getFieldDesc(HeightDataFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleHeightData     (void)
{
    SFUnrecImagePtr::EditHandlePtr returnValue(
        new  SFUnrecImagePtr::EditHandle(
             &_sfHeightData,
             this->getType().getFieldDesc(HeightDataFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&DynamicTerrain::setHeightData,
                    static_cast<DynamicTerrain *>(this), _1));

    editSField(HeightDataFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleHeightDataScale (void) const
{
    SFReal32::GetHandlePtr returnValue(
        new  SFReal32::GetHandle(
             &_sfHeightDataScale,
             this->getType().getFieldDesc(HeightDataScaleFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleHeightDataScale(void)
{
    SFReal32::EditHandlePtr returnValue(
        new  SFReal32::EditHandle(
             &_sfHeightDataScale,
             this->getType().getFieldDesc(HeightDataScaleFieldId),
             this));


    editSField(HeightDataScaleFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleHeightDataOffset (void) const
{
    SFReal32::GetHandlePtr returnValue(
        new  SFReal32::GetHandle(
             &_sfHeightDataOffset,
             this->getType().getFieldDesc(HeightDataOffsetFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleHeightDataOffset(void)
{
    SFReal32::EditHandlePtr returnValue(
        new  SFReal32::EditHandle(
             &_sfHeightDataOffset,
             this->getType().getFieldDesc(HeightDataOffsetFieldId),
             this));


    editSField(HeightDataOffsetFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleSampleDistance  (void) const
{
    SFReal32::GetHandlePtr returnValue(
        new  SFReal32::GetHandle(
             &_sfSampleDistance,
             this->getType().getFieldDesc(SampleDistanceFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleSampleDistance (void)
{
    SFReal32::EditHandlePtr returnValue(
        new  SFReal32::EditHandle(
             &_sfSampleDistance,
             this->getType().getFieldDesc(SampleDistanceFieldId),
             this));


    editSField(SampleDistanceFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleTextureData     (void) const
{
    SFUnrecImagePtr::GetHandlePtr returnValue(
        new  SFUnrecImagePtr::GetHandle(
             &_sfTextureData,
             this->getType().getFieldDesc(TextureDataFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleTextureData    (void)
{
    SFUnrecImagePtr::EditHandlePtr returnValue(
        new  SFUnrecImagePtr::EditHandle(
             &_sfTextureData,
             this->getType().getFieldDesc(TextureDataFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&DynamicTerrain::setTextureData,
                    static_cast<DynamicTerrain *>(this), _1));

    editSField(TextureDataFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleHeightColorTexture (void) const
{
    SFUnrecTextureObjChunkPtr::GetHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::GetHandle(
             &_sfHeightColorTexture,
             this->getType().getFieldDesc(HeightColorTextureFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleHeightColorTexture(void)
{
    SFUnrecTextureObjChunkPtr::EditHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::EditHandle(
             &_sfHeightColorTexture,
             this->getType().getFieldDesc(HeightColorTextureFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&DynamicTerrain::setHeightColorTexture,
                    static_cast<DynamicTerrain *>(this), _1));

    editSField(HeightColorTextureFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleSampleUpdateBudget (void) const
{
    SFInt32::GetHandlePtr returnValue(
        new  SFInt32::GetHandle(
             &_sfSampleUpdateBudget,
             this->getType().getFieldDesc(SampleUpdateBudgetFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleSampleUpdateBudget(void)
{
    SFInt32::EditHandlePtr returnValue(
        new  SFInt32::EditHandle(
             &_sfSampleUpdateBudget,
             this->getType().getFieldDesc(SampleUpdateBudgetFieldId),
             this));


    editSField(SampleUpdateBudgetFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleEnableFrustumCulling (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfEnableFrustumCulling,
             this->getType().getFieldDesc(EnableFrustumCullingFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleEnableFrustumCulling(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfEnableFrustumCulling,
             this->getType().getFieldDesc(EnableFrustumCullingFieldId),
             this));


    editSField(EnableFrustumCullingFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleUseGpuRenderer  (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfUseGpuRenderer,
             this->getType().getFieldDesc(UseGpuRendererFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleUseGpuRenderer (void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfUseGpuRenderer,
             this->getType().getFieldDesc(UseGpuRendererFieldId),
             this));


    editSField(UseGpuRendererFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleUseVboExtension (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfUseVboExtension,
             this->getType().getFieldDesc(UseVboExtensionFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleUseVboExtension(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfUseVboExtension,
             this->getType().getFieldDesc(UseVboExtensionFieldId),
             this));


    editSField(UseVboExtensionFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleEnableSmoothTransition (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfEnableSmoothTransition,
             this->getType().getFieldDesc(EnableSmoothTransitionFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleEnableSmoothTransition(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfEnableSmoothTransition,
             this->getType().getFieldDesc(EnableSmoothTransitionFieldId),
             this));


    editSField(EnableSmoothTransitionFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleShowBoundingBoxes (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfShowBoundingBoxes,
             this->getType().getFieldDesc(ShowBoundingBoxesFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleShowBoundingBoxes(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfShowBoundingBoxes,
             this->getType().getFieldDesc(ShowBoundingBoxesFieldId),
             this));


    editSField(ShowBoundingBoxesFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleShowTransitionRegions (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfShowTransitionRegions,
             this->getType().getFieldDesc(ShowTransitionRegionsFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleShowTransitionRegions(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfShowTransitionRegions,
             this->getType().getFieldDesc(ShowTransitionRegionsFieldId),
             this));


    editSField(ShowTransitionRegionsFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleDisableUpdate   (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfDisableUpdate,
             this->getType().getFieldDesc(DisableUpdateFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleDisableUpdate  (void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfDisableUpdate,
             this->getType().getFieldDesc(DisableUpdateFieldId),
             this));


    editSField(DisableUpdateFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleCpuVertexProgram (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfCpuVertexProgram,
             this->getType().getFieldDesc(CpuVertexProgramFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleCpuVertexProgram(void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfCpuVertexProgram,
             this->getType().getFieldDesc(CpuVertexProgramFieldId),
             this));


    editSField(CpuVertexProgramFieldMask);

    return returnValue;
}

GetFieldHandlePtr DynamicTerrainBase::getHandleCpuFragmentProgram (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfCpuFragmentProgram,
             this->getType().getFieldDesc(CpuFragmentProgramFieldId),
             const_cast<DynamicTerrainBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DynamicTerrainBase::editHandleCpuFragmentProgram(void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfCpuFragmentProgram,
             this->getType().getFieldDesc(CpuFragmentProgramFieldId),
             this));


    editSField(CpuFragmentProgramFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void DynamicTerrainBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    DynamicTerrain *pThis = static_cast<DynamicTerrain *>(this);

    pThis->execSync(static_cast<DynamicTerrain *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *DynamicTerrainBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    DynamicTerrain *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const DynamicTerrain *>(pRefAspect),
                  dynamic_cast<const DynamicTerrain *>(this));

    return returnValue;
}
#endif

void DynamicTerrainBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<DynamicTerrain *>(this)->setHeightData(NULL);

    static_cast<DynamicTerrain *>(this)->setTextureData(NULL);

    static_cast<DynamicTerrain *>(this)->setHeightColorTexture(NULL);


}


OSG_END_NAMESPACE
