/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTRIPSAUDIOSYSTEMFIELDS_H_
#define _OSGTRIPSAUDIOSYSTEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGTRIPSDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TRIPSAudioSystem;

OSG_GEN_CONTAINERPTR(TRIPSAudioSystem);

/*! \ingroup GrpTRIPSFieldTraits
    \ingroup GrpLibOSGTRIPS
 */
template <>
struct FieldTraits<TRIPSAudioSystem *> :
    public FieldTraitsFCPtrBase<TRIPSAudioSystem *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TRIPSAudioSystem *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_TRIPS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTRIPSAudioSystemPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTRIPSAudioSystemPtr"; }
};

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTRIPSAudioSystemPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTRIPSAudioSystemPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTRIPSAudioSystemPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTRIPSAudioSystemPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTRIPSAudioSystemPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTRIPSAudioSystemPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTRIPSAudioSystemPtr"; 
}

template<> inline
const Char8 *FieldTraits<TRIPSAudioSystem *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTRIPSAudioSystemPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSAudioSystem *,
                      RecordedRefCountPolicy  > SFRecTRIPSAudioSystemPtr;
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSAudioSystem *,
                      UnrecordedRefCountPolicy> SFUnrecTRIPSAudioSystemPtr;
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSAudioSystem *,
                      WeakRefCountPolicy      > SFWeakTRIPSAudioSystemPtr;
/*! \ingroup GrpTRIPSFieldSFields */
typedef PointerSField<TRIPSAudioSystem *,
                      NoRefCountPolicy        > SFUncountedTRIPSAudioSystemPtr;


/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSAudioSystem *,
                      RecordedRefCountPolicy  > MFRecTRIPSAudioSystemPtr;
/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSAudioSystem *,
                      UnrecordedRefCountPolicy> MFUnrecTRIPSAudioSystemPtr;
/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSAudioSystem *,
                      WeakRefCountPolicy      > MFWeakTRIPSAudioSystemPtr;
/*! \ingroup GrpTRIPSFieldMFields */
typedef PointerMField<TRIPSAudioSystem *,
                      NoRefCountPolicy        > MFUncountedTRIPSAudioSystemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFRecTRIPSAudioSystemPtr : 
    public PointerSField<TRIPSAudioSystem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFUnrecTRIPSAudioSystemPtr : 
    public PointerSField<TRIPSAudioSystem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFWeakTRIPSAudioSystemPtr :
    public PointerSField<TRIPSAudioSystem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldSFields \ingroup GrpLibOSGTRIPS */
struct SFUncountedTRIPSAudioSystemPtr :
    public PointerSField<TRIPSAudioSystem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFRecTRIPSAudioSystemPtr :
    public PointerMField<TRIPSAudioSystem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFUnrecTRIPSAudioSystemPtr :
    public PointerMField<TRIPSAudioSystem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFWeakTRIPSAudioSystemPtr :
    public PointerMField<TRIPSAudioSystem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpTRIPSFieldMFields \ingroup GrpLibOSGTRIPS */
struct MFUncountedTRIPSAudioSystemPtr :
    public PointerMField<TRIPSAudioSystem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTRIPSAUDIOSYSTEMFIELDS_H_ */
