/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGRTCACHEATTACHMENTFIELDS_H_
#define _OSGRTCACHEATTACHMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribRRTDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class RTCacheAttachment;

OSG_GEN_CONTAINERPTR(RTCacheAttachment);

/*! \ingroup GrpContribRRTFieldTraits
    \ingroup GrpLibOSGContribRRT
 */
template <>
struct FieldTraits<RTCacheAttachment *> :
    public FieldTraitsFCPtrBase<RTCacheAttachment *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<RTCacheAttachment *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBRRT_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFRTCacheAttachmentPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFRTCacheAttachmentPtr"; }
};

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRTCacheAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRTCacheAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRTCacheAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRTCacheAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecRTCacheAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecRTCacheAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakRTCacheAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCacheAttachment *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdRTCacheAttachmentPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheAttachment *,
                      RecordedRefCountPolicy  > SFRecRTCacheAttachmentPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheAttachment *,
                      UnrecordedRefCountPolicy> SFUnrecRTCacheAttachmentPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheAttachment *,
                      WeakRefCountPolicy      > SFWeakRTCacheAttachmentPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCacheAttachment *,
                      NoRefCountPolicy        > SFUncountedRTCacheAttachmentPtr;


/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheAttachment *,
                      RecordedRefCountPolicy  > MFRecRTCacheAttachmentPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheAttachment *,
                      UnrecordedRefCountPolicy> MFUnrecRTCacheAttachmentPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheAttachment *,
                      WeakRefCountPolicy      > MFWeakRTCacheAttachmentPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCacheAttachment *,
                      NoRefCountPolicy        > MFUncountedRTCacheAttachmentPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFRecRTCacheAttachmentPtr : 
    public PointerSField<RTCacheAttachment *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUnrecRTCacheAttachmentPtr : 
    public PointerSField<RTCacheAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFWeakRTCacheAttachmentPtr :
    public PointerSField<RTCacheAttachment *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUncountedRTCacheAttachmentPtr :
    public PointerSField<RTCacheAttachment *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFRecRTCacheAttachmentPtr :
    public PointerMField<RTCacheAttachment *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUnrecRTCacheAttachmentPtr :
    public PointerMField<RTCacheAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFWeakRTCacheAttachmentPtr :
    public PointerMField<RTCacheAttachment *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUncountedRTCacheAttachmentPtr :
    public PointerMField<RTCacheAttachment *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGRTCACHEATTACHMENTFIELDS_H_ */
