/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class RTCameraDecorator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGRTCameraDecoratorBase.h"
#include "OSGRTCameraDecorator.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::RTCameraDecorator
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<RTCameraDecorator *, nsOSG>::_type("RTCameraDecoratorPtr", "CameraDecoratorPtr", nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(RTCameraDecorator *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           RTCameraDecorator *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           RTCameraDecorator *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void RTCameraDecoratorBase::classDescInserter(TypeObject &oType)
{
}


RTCameraDecoratorBase::TypeObject RTCameraDecoratorBase::_type(
    RTCameraDecoratorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&RTCameraDecoratorBase::createEmptyLocal),
    RTCameraDecorator::initMethod,
    RTCameraDecorator::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&RTCameraDecorator::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"RTCameraDecorator\"\n"
    "\tparent=\"CameraDecorator\"\n"
    "\tlibrary=\"ContribRRT\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"true\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &RTCameraDecoratorBase::getType(void)
{
    return _type;
}

const FieldContainerType &RTCameraDecoratorBase::getType(void) const
{
    return _type;
}

UInt32 RTCameraDecoratorBase::getContainerSize(void) const
{
    return sizeof(RTCameraDecorator);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 RTCameraDecoratorBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void RTCameraDecoratorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void RTCameraDecoratorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
RTCameraDecoratorTransitPtr RTCameraDecoratorBase::createLocal(BitVector bFlags)
{
    RTCameraDecoratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<RTCameraDecorator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
RTCameraDecoratorTransitPtr RTCameraDecoratorBase::createDependent(BitVector bFlags)
{
    RTCameraDecoratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<RTCameraDecorator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
RTCameraDecoratorTransitPtr RTCameraDecoratorBase::create(void)
{
    RTCameraDecoratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<RTCameraDecorator>(tmpPtr);
    }

    return fc;
}

RTCameraDecorator *RTCameraDecoratorBase::createEmptyLocal(BitVector bFlags)
{
    RTCameraDecorator *returnValue;

    newPtr<RTCameraDecorator>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
RTCameraDecorator *RTCameraDecoratorBase::createEmpty(void)
{
    RTCameraDecorator *returnValue;

    newPtr<RTCameraDecorator>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr RTCameraDecoratorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    RTCameraDecorator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const RTCameraDecorator *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr RTCameraDecoratorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    RTCameraDecorator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const RTCameraDecorator *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr RTCameraDecoratorBase::shallowCopy(void) const
{
    RTCameraDecorator *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const RTCameraDecorator *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

RTCameraDecoratorBase::RTCameraDecoratorBase(void) :
    Inherited()
{
}

RTCameraDecoratorBase::RTCameraDecoratorBase(const RTCameraDecoratorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

RTCameraDecoratorBase::~RTCameraDecoratorBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void RTCameraDecoratorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    RTCameraDecorator *pThis = static_cast<RTCameraDecorator *>(this);

    pThis->execSync(static_cast<RTCameraDecorator *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *RTCameraDecoratorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    RTCameraDecorator *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const RTCameraDecorator *>(pRefAspect),
                  dynamic_cast<const RTCameraDecorator *>(this));

    return returnValue;
}
#endif

void RTCameraDecoratorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
