/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGRTINFOATTACHMENTFIELDS_H_
#define _OSGRTINFOATTACHMENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribRRTDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class RTInfoAttachment;

OSG_GEN_CONTAINERPTR(RTInfoAttachment);

/*! \ingroup GrpContribRRTFieldTraits
    \ingroup GrpLibOSGContribRRT
 */
template <>
struct FieldTraits<RTInfoAttachment *> :
    public FieldTraitsFCPtrBase<RTInfoAttachment *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<RTInfoAttachment *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBRRT_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFRTInfoAttachmentPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFRTInfoAttachmentPtr"; }
};

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRTInfoAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRTInfoAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRTInfoAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRTInfoAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecRTInfoAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecRTInfoAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakRTInfoAttachmentPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTInfoAttachment *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdRTInfoAttachmentPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTInfoAttachment *,
                      RecordedRefCountPolicy  > SFRecRTInfoAttachmentPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTInfoAttachment *,
                      UnrecordedRefCountPolicy> SFUnrecRTInfoAttachmentPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTInfoAttachment *,
                      WeakRefCountPolicy      > SFWeakRTInfoAttachmentPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTInfoAttachment *,
                      NoRefCountPolicy        > SFUncountedRTInfoAttachmentPtr;


/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTInfoAttachment *,
                      RecordedRefCountPolicy  > MFRecRTInfoAttachmentPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTInfoAttachment *,
                      UnrecordedRefCountPolicy> MFUnrecRTInfoAttachmentPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTInfoAttachment *,
                      WeakRefCountPolicy      > MFWeakRTInfoAttachmentPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTInfoAttachment *,
                      NoRefCountPolicy        > MFUncountedRTInfoAttachmentPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFRecRTInfoAttachmentPtr : 
    public PointerSField<RTInfoAttachment *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUnrecRTInfoAttachmentPtr : 
    public PointerSField<RTInfoAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFWeakRTInfoAttachmentPtr :
    public PointerSField<RTInfoAttachment *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUncountedRTInfoAttachmentPtr :
    public PointerSField<RTInfoAttachment *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFRecRTInfoAttachmentPtr :
    public PointerMField<RTInfoAttachment *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUnrecRTInfoAttachmentPtr :
    public PointerMField<RTInfoAttachment *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFWeakRTInfoAttachmentPtr :
    public PointerMField<RTInfoAttachment *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUncountedRTInfoAttachmentPtr :
    public PointerMField<RTInfoAttachment *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGRTINFOATTACHMENTFIELDS_H_ */
