/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGRTCAMERADECORATORFIELDS_H_
#define _OSGRTCAMERADECORATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribRRTDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class RTCameraDecorator;

OSG_GEN_CONTAINERPTR(RTCameraDecorator);
/*! \ingroup GrpContribRRTFieldTraits
    \ingroup GrpLibOSGContribRRT
 */
template <>
struct FieldTraits<RTCameraDecorator *, nsOSG> :
    public FieldTraitsFCPtrBase<RTCameraDecorator *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<RTCameraDecorator *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBRRT_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRTCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRTCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRTCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRTCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecRTCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecRTCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakRTCameraDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<RTCameraDecorator *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdRTCameraDecoratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCameraDecorator *,
                      RecordedRefCountPolicy, nsOSG  > SFRecRTCameraDecoratorPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCameraDecorator *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecRTCameraDecoratorPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCameraDecorator *,
                      WeakRefCountPolicy, nsOSG      > SFWeakRTCameraDecoratorPtr;
/*! \ingroup GrpContribRRTFieldSFields */
typedef PointerSField<RTCameraDecorator *,
                      NoRefCountPolicy, nsOSG        > SFUncountedRTCameraDecoratorPtr;


/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCameraDecorator *,
                      RecordedRefCountPolicy, nsOSG  > MFRecRTCameraDecoratorPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCameraDecorator *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecRTCameraDecoratorPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCameraDecorator *,
                      WeakRefCountPolicy, nsOSG      > MFWeakRTCameraDecoratorPtr;
/*! \ingroup GrpContribRRTFieldMFields */
typedef PointerMField<RTCameraDecorator *,
                      NoRefCountPolicy, nsOSG        > MFUncountedRTCameraDecoratorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFRecRTCameraDecoratorPtr : 
    public PointerSField<RTCameraDecorator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUnrecRTCameraDecoratorPtr : 
    public PointerSField<RTCameraDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFWeakRTCameraDecoratorPtr :
    public PointerSField<RTCameraDecorator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldSFields \ingroup GrpLibOSGContribRRT */
struct SFUncountedRTCameraDecoratorPtr :
    public PointerSField<RTCameraDecorator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFRecRTCameraDecoratorPtr :
    public PointerMField<RTCameraDecorator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUnrecRTCameraDecoratorPtr :
    public PointerMField<RTCameraDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFWeakRTCameraDecoratorPtr :
    public PointerMField<RTCameraDecorator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribRRTFieldMFields \ingroup GrpLibOSGContribRRT */
struct MFUncountedRTCameraDecoratorPtr :
    public PointerMField<RTCameraDecorator *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGRTCAMERADECORATORFIELDS_H_ */
